### ISSUE TITLE
RangeError, getting SIGTERM...

### ISSUE THREAD

**Issue by itaiLandau** [kiwi-cam/homebridge-broadlink-rm#115]
after running for a bit, Hoobs will output this log:
2020-11-21, 4:27:27 PM RangeError [ERR_INVALID_OPT_VALUE]: The value "-47" is invalid for option "size"
    at Function.alloc (buffer.js:373:3)
    at Socket.<anonymous> (/Users/erezlandau/.hoobs/node_modules/kiwicam-broadlinkjs-rm/index.js:293:39)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:919:8)
2020-11-21, 4:27:27 PM Got SIGTERM, shutting down Bridge...

Iv'e attached my config
[config.json.zip](https://github.com/kiwi-cam/homebridge-broadlink-rm/files/5577810/config.json.zip)

**Comment by kiwi-cam** [comment]
This is odd. Basically the plugin is getting a packet that is smaller than expected.  I've added some error handling in the latest beta which will ignore these invalid packets.

**Comment by kiwi-cam** [comment]
This should now be fixed in 4.3.8

**Comment by itaiLandau** [comment]
I'm running 4.3.8
still getting the same error.

**Comment by itaiLandau** [comment]
I've edited the source code and added the line "if (response.length <= 0x38) return;" at index.js:293, seems to work for now, will report back if it fails again.

**Comment by kiwi-cam** [comment]
Haha, you found my error (no HEX conversion 🤦‍♂️) I've just done the same in Git - I'll push a new BETA soon.

**Comment by itaiLandau** [comment]
Nice, great to have been of help 👍
