### ISSUE TITLE
problem on plugin shoutdown

### ISSUE THREAD

**Issue by platini76** [kiwi-cam/homebridge-broadlink-rm#129]
[4/12/2020, 00:48:37] Error: EMFILE: too many open files, open '/var/lib/homebridge/plugin-persist/homebridge-broadlink-rm/73d91947c90cc984abdfd51c3f064b66'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at LocalStorage.persistKeySync (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/node-persist/src/local-storage.js:471:16)
    at LocalStorage.setItemSync (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/node-persist/src/local-storage.js:255:14)
    at Object.save (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/homebridge-platform-helper/helpers/persistentState.js:30:22)
    at /usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/homebridge-platform-helper/accessory.js:183:23
    at Object.set (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/homebridge-platform-helper/accessory.js:9:7)
    at AirConAccessory.onTemperature (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:379:30)
    at Device.emit (events.js:315:20)
    at Device.onPayloadReceived (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/kiwicam-broadlinkjs-rm/index.js:471:14)
[4/12/2020, 00:48:38] Got SIGTERM, shutting down Homebridge...

how to solve?

**Comment by kiwi-cam** [comment]
I don't suppose this could be related to this: https://github.com/oznu/homebridge-config-ui-x/issues/321 ?
