### ISSUE TITLE
crash during scan frequency

### ISSUE THREAD

**Issue by Cyberbeni** [kiwi-cam/homebridge-broadlink-rm#150]
Probably because success was at the same time as timeout
```console
12/12/2020, 15:16:19 [Broadlink RM] [INFO] Scan RF (complete)
12/12/2020, 15:16:19 [Broadlink RM] [RESULT] Hex Code: [filtered]
12/12/2020, 15:16:20 [Broadlink RM] [INFO] Scan RF (stopped)
12/12/2020, 15:16:20 [Broadlink RM] [INFO] Scan RF (stopped - 20s timeout)
12/12/2020, 15:16:20 TypeError: closeClient is not a function
    at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm-pro/helpers/learnRFData.js:135:7)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
12/12/2020, 15:16:20 Got SIGTERM, shutting down Bridge...
```

**Comment by masterfordev** [comment]
Plugin Version?

**Comment by Cyberbeni** [comment]
4.3.8

**Comment by masterfordev** [comment]
Try using the beta version.

**Comment by Cyberbeni** [comment]
I have already scanned everything and it already happened once out of like 30 scans, so I can't really test it out.
