### ISSUE TITLE
Cannot read property length of undefined when turning AC on

### ISSUE THREAD

**Issue by alex-tan** [kiwi-cam/homebridge-broadlink-rm#205]
I think the code is attempting to fetch the current temperature of the AC but is unable to because the AC only has a pseudoDeviceTemperature. I have no problem turning the AC off, however.

Homebridge v1.1.7
homebridge-broadlink-rm-pro v4.4.0

AC config:

```json
                {
                    "name": "Air Conditioner",
                    "host": "192.168.0.107",
                    "type": "air-conditioner",
                    "data": {
                        "minTemperature": 17,
                        "maxTemperature": 24,
                        "temperatureDisplayUnits": "C",
                        "turnOnWhenOff": true,
                        "pseudoDeviceTemperature": 19,
                        "defaultCoolTemperature": 19,
                        "defaultHeatTemperature": 19,
                        "temperatureUpdateFrequency": 1000,
                        "on": "2600220191590b0f0a100911091109110912081208120a1008120a1009110a1009110c0e0b1008120b0f08120a100812091109110c0e0b100a1008120a100a1008120a100b0f0a100b0f0b0f0b100b0f0a100a100a100b0f0b0f0b0f0c0e0b100b0f0a100a100a100b0f0b0f0b0f0c0e0b100a100a100a100a100b0f0b0f0c0e0b0f0b0f0b100b0f0b0f0b0f0b0f0b0f0c0e0c0e0c0e0c0f0b0f0a100b0f0b0f0c0e0c0e0c0e0c0e0c0f0b0f0b0f0c0e0c0e0c0e0c0e0c0e0c0e0b100b0f0b0f0b0f0c0e0c0e0c0e0c0e0c0f0b0f0b0f0c0e0c0e0c0e0c0e0a110b0f0b0f0b0f0c0e0c0e0c0e0c0e0c0f0b0f0c0e0c2608120812092a09110c0e0c0f0b270812082b09110b0f0c0e0c0e0c0e0c0e0c26092a09110c0f0b0f0b27082b09110c0002a784000d05000000000000",
                        "off": "2600220191590b0f0a100911091109110912081208120a1008120a1009110a1009110c0e0b1008120b0f08120a100812091109110c0e0b100a1008120a100a1008120a100b0f0a100b0f0b0f0b100b0f0a100a100a100b0f0b0f0b0f0c0e0b100b0f0a100a100a100b0f0b0f0b0f0c0e0b100a100a100a100a100b0f0b0f0c0e0b0f0b0f0b100b0f0b0f0b0f0b0f0b0f0c0e0c0e0c0e0c0f0b0f0a100b0f0b0f0c0e0c0e0c0e0c0e0c0f0b0f0b0f0c0e0c0e0c0e0c0e0c0e0c0e0b100b0f0b0f0b0f0c0e0c0e0c0e0c0e0c0f0b0f0b0f0c0e0c0e0c0e0c0e0a110b0f0b0f0b0f0c0e0c0e0c0e0c0e0c0f0b0f0c0e0c2608120812092a09110c0e0c0f0b270812082b09110b0f0c0e0c0e0c0e0c0e0c26092a09110c0f0b0f0b27082b09110c0002a784000d05000000000000",
                        "temperature16": "26002201905a0812081209110a11081209110812081208120912081208120812091109110a100912081209110812091109120911081208120812091109110912081209110812081209110912091108120911081209120812081208120812081209110a11081208120911091109110912091108120812081209110a1108120812081209110a100912081208120911091109110912081208120812081209110912081209110812091109110a1109110911081209110911091208120812081209110a100912081207130812091109110912091108120812091109110912081209110812081209110912071308120812082a091208120812091207130713082a0911092a09110813072b072c072b0911082b071308120812082a082b08130713070002ac86000d05000000000000",
                        "temperature17": "26002201905a0812081209110a11081209110812081208120912081208120812091109110a100912081209110812091109120911081208120812091109110912081209110812081209110912091108120911081209120812081208120812081209110a11081208120911091109110912091108120812081209110a1108120812081209110a100912081208120911091109110912081208120812081209110912081209110812091109110a1109110911081209110911091208120812081209110a100912081207130812091109110912091108120812091109110912081209110812081209110912071308120812082a091208120812091207130713082a0911092a09110813072b072c072b0911082b071308120812082a082b08130713070002ac86000d05000000000000",
                        "temperature19": "2600220191590a100b0f09110a11081208120a1009110b0f091208120a10081209110b0f0a100912081208120911091109110911091208120812081209110911091208120812081209110911091109120812081208120911091109120812081208120911091109110912081208120812091109110912081208120812091109110911091208120812091108120911091208120812081209110911091109120812081209110911091109120812081208120911091109120812081208120911091109120812081208120911091109110912081208120911091109110912081208120812091109110912081208120812092908120912082a0b1008120812082a0911082b0a100911092a08120812082b0a28081208120812092a0a10092a082a0b0002a985000d05000000000000",
                        "temperature24": "26001a019059071406150811061407140613071507120614071507110713081407130614071307130714081107140911061506120813061308150712061506130713081307120615071306140712071409110911071406160712071207130813072e090d08150714081205150614081107140812091208120713071406140712071309120614062e0716080f061607140612061407140713071406140613081406130713081206150613081207130912061509100615071207490713061407110714081207140a11081107120714071407140614071208120813071206160614061406130713072d081207140613061507120714072a0812062e0713061505140614072b07140713062c06150614072d071207120714070002ac84000d050000000000000000000000000000"
                    }
                }
```

Error:

```bash
(node:96654) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:52:40
    at catchDelayCancelError (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/helpers/catchDelayCancelError.js:8:20)
    at AirConAccessory.performSend (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:50:11)
    at AirConAccessory.sendTemperature (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:285:18)
    at /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:250:14
(node:96654) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by kiwi-cam** [comment]
What is in the log immediately before the error? Looks like it's trying to send a temperature that you don't have a code configured for.

**Comment by alex-tan** [comment]
```
[1/27/2021, 12:56:24 PM] [Broadlink RM] Air Conditioner sentMode (cool)
[1/27/2021, 12:56:24 PM] [Broadlink RM] Air Conditioner getCurrentHeatingCoolingState: 0
[1/27/2021, 12:56:24 PM] [Broadlink RM] Air Conditioner getTargetHeatingCoolingState: 2
[1/27/2021, 12:56:25 PM] [Broadlink RM] Air Conditioner setCurrentHeatingCoolingState: 2
[1/27/2021, 12:56:25 PM] [Broadlink RM] Air Conditioner No cool HEX code found for 16
[1/27/2021, 12:56:25 PM] [Broadlink RM] Air Conditioner getTargetTemperature: 16
(node:282) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
```

Although I updated to 4.4.1 and it looks like the error went away. Thanks!
