### ISSUE TITLE
Plugin unable to start (Homebridge 1.3 not running untill disabled or removed plugin)

### ISSUE THREAD

**Issue by Mikellas** [kiwi-cam/homebridge-broadlink-rm#239]
I have updated to Homebridge 1.3
This plugin is the only one not starting causing Homebridge to not boot
This also happens when I isolate the plugin via bridge settings

Log returns with a [Broadlink RM] homebridge-broadlink-rm-pro is taking a long time to load and preventing Homebridge from starting.

-Homebridge is installed on a Windows 10 PC
-I use Edge as a browser
-All was working fine prior 1.3

Let me know if any other log is required to assist on this

**Comment by kiwi-cam** [comment]
This is surprising. I’ve run two of the beta releases without issue. Unfortunately I’m not going to have a chance to investigate for a few days.

**Comment by Mikellas** [comment]
Is there something i can do to assist on this?

**Comment by lwitzani** [comment]
Hello, 
i just updated to homebridge 1.3 and this plugin works. Do you have the latest version @Mikellas ?

Unfortunately i have another issue with the plugin which i described in #240

**Comment by Mikellas** [comment]
Yeap latest version 
I also tried adding it as a child bridge
This is what i get when I enable hb debug

[homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.
[2/20/2021, 4:28:53 PM] [homebridge-broadlink-rm-pro] Error: 
    at CurrentRelativeHumidity.Characteristic.characteristicWarning (C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:2063:79)
    at CurrentRelativeHumidity.Characteristic.validateUserInput (C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1839:12)
    at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1490:24
    at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\util\once.ts:9:18
    at AirConAccessory.getCurrentHumidity (C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm-pro\accessories\aircon.js:564:12)
    at CurrentRelativeHumidity.emit (events.js:314:20)
    at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1466:14
    at new Promise (<anonymous>)
    at CurrentRelativeHumidity.<anonymous> (C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:1464:12)
    at step (C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:143:27)

**Comment by Mikellas** [comment]
Ok this is weird although Homebridge plugin states that [Broadlink RM] homebridge-broadlink-rm-pro is taking a long time to load and preventing Homebridge from starting,after I disable Homebridge Xiaomi Roborock Vacuum plugin all works well

Dont know if there is a relationship between the two but thats weird

**Comment by lwitzani** [comment]
I also have the roborock plugin running. At my side everything works now

**Comment by Mikellas** [comment]
Well i started disabling plugins untill Homebridge finally booted up.The roborock plugin is the only one not allowing Homebridge to proceed so i went ahead and added it to a child bridge .Although the bridge does not give me a barcode to scan homebridge at least works fine

**Comment by Mikellas** [comment]
Ok figured out exactly whats causing this I believe
Its the startdelay which is a beta feature for the roborock
