### ISSUE TITLE
Temperature on the App on HomeKit wrong and other issues

### ISSUE THREAD

**Issue by mikeosude** [kiwi-cam/homebridge-broadlink-rm#253]
I am using this plugin on home bridge, the system has been setup, the TV is working fine and other accessories that use IR are ok but the only one I cannot get to work properly is the AC.

I have an LG AC the Temp is from 16 to 30 Celsius. and I have temperature and humidity sensors on the RM4 Pro which the app is collecting and sending to the AC. on the home app my temperature is in the 80s and my AC heats to 122 and cools to 51, I have tried everything, on home bridge it seems to work fine but on the app it is all over the place. also, the slider for the temperature isn't working because the home app temperature is higher than the one set in the plugin, please how do I rectify this?

Setting:
{
            "name": "LG AC",
            "type": "air-conditioner",
            "turnOnWhenOff": true,
            "coolOnly": true,
            "noHumidity": false,
            "minTemperature": 0,
            "maxTemperature": 50,
            "defaultCoolTemperature": 16,
            "defaultHeatTemperature": 30,
            "temperatureUpdateFrequency": 10,
            "data": {
                "temperatureDisplayUnits": "C",
                "pseudoDeviceTemperature": 30.6,
                "on": "260040006a00014411341011111210121033111111120f131011111210120f1210121012101210121012101210340f3410121033111210120f1210341034103410000d05000000000000",
                "off": "2600400067000140103311121012101210340f130f1210121034103410120f1210121012101210121012101210111111111210341012103310121012101210340f000d05000000000000",
                "temperature30": {
                    "pseudo-mode": "heat",
                    "temperature30": "26004000640001431133111210120f1210341112101210120f1210121012101210340f13101111120f341034103310121112103310121012103310130f34101210000d05000000000000"
                },
                "temperature16": {
                    "pseudo-mode": "cool",
                    "temperature16": "260040006b000143103411121012101210340f131011101210121012101210121033101210121012101210120f130f341012103311121012103410331012103410000d05000000000000"
                }
            }
        }

Temperature from the plugin:
[2/27/2021, 2:19:37 AM] [BroadlinkRM] LG AC onTemperature (30.14)
[2/27/2021, 2:19:37 AM] [BroadlinkRM] LG AC onHumidity (29.91)
[2/27/2021, 2:19:47 AM] [BroadlinkRM] LG AC onTemperature (30.15)
[2/27/2021, 2:19:47 AM] [BroadlinkRM] LG AC onHumidity (29.92)
[2/27/2021, 2:19:57 AM] [BroadlinkRM] LG AC onTemperature (30.15)
[2/27/2021, 2:19:57 AM] [BroadlinkRM] LG AC onHumidity (29.92)
[2/27/2021, 2:20:07 AM] [BroadlinkRM] LG AC onTemperature (30.15)
[2/27/2021, 2:20:07 AM] [BroadlinkRM] LG AC onHumidity (29.92)
[2/27/2021, 2:20:17 AM] [BroadlinkRM] LG AC onTemperature (30.15)
[2/27/2021, 2:20:17 AM] [BroadlinkRM] LG AC onHumidity (29.92)
[2/27/2021, 2:20:27 AM] [BroadlinkRM] LG AC onTemperature (30.15)
[2/27/2021, 2:20:27 AM] [BroadlinkRM] LG AC onHumidity (29.92)
[2/27/2021, 2:20:37 AM] [BroadlinkRM] LG AC onTemperature (30.15)
[2/27/2021, 2:20:37 AM] [BroadlinkRM] LG AC onHumidity (29.92)
[2/27/2021, 2:20:47 AM] [BroadlinkRM] LG AC onTemperature (30.15)
[2/27/2021, 2:20:47 AM] [BroadlinkRM] LG AC onHumidity (29.93)
[2/27/2021, 2:20:57 AM] [BroadlinkRM] LG AC onTemperature (30.15)
[2/27/2021, 2:20:57 AM] [BroadlinkRM] LG AC onHumidity (29.93)

Temperature on Home app:
86

When trying to change temperature:
 [BroadlinkRM] LG AC setTargetTemperature: 13
[2/27/2021, 2:22:16 AM] [BroadlinkRM] LG AC No cool HEX code found for 13
[2/27/2021, 2:22:16 AM] [BroadlinkRM] LG AC Update to default temperature (16)
[2/27/2021, 2:22:16 AM] [BroadlinkRM] LG AC getTargetTemperature: 16
(node:15552) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:52:40
    at catchDelayCancelError (/usr/lib/node_modules/homebridge-broadlink-rm-pro/helpers/catchDelayCancelError.js:8:20)
    at AirConAccessory.performSend (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:50:11)
    at AirConAccessory.sendTemperature (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:285:18)
    at AirConAccessory.setTargetTemperature (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:181:10)
    at AirConAccessory.setCharacteristicValue (/usr/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:136:10)
    at TargetTemperature.emit (events.js:315:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1615:16
    at new Promise (<anonymous>)
    at TargetTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1613:14)
(node:15552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

![IMG_36DE6875AA18-1](https://user-images.githubusercontent.com/11045451/109370969-efe92080-78a2-11eb-9fdb-3770608b6b30.jpeg)

IR: Broadlink RM4 pro (Living Room) and RM4 mini (Bedroom)

Server: Raspberry Pi 4
OS: Ubuntu 20.04 LTS
Node version: 14
NPM version: 6

AC: LG AC (won't accept any commands without on first)

Please I really need help with this issue as it has been bugging me for weeks now

**Comment by masterfordev** [comment]
The Home apps shows the temperature in "Fahrenheit" and the plugin is configured in "Celsius" ?. And when you are using the temperature from sensors, you should not use config `"pseudoDeviceTemperature": 30.6,`.
