### ISSUE TITLE
getSwitchState: undefined / This plugin generated a warning from the characteristic 'On'

### ISSUE THREAD

**Issue by soulcook** [kiwi-cam/homebridge-broadlink-rm#260]
**Describe the bug**
The plugin is logging `getSwitchState: undefined` and Homebridge is logging `This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined.`.

Relevant log except below. This happens immediately after Homebridge is started, and intermittently after that. It doesn't seem to be associated with actually using the accessories, which work fine.

Issues similar to this seem to have been raised before, but I haven't seen a resolution.

```
[3/3/2021, 10:52:02 AM] [Broadlink RM] Projector On getSwitchState: undefined
[3/3/2021, 10:52:02 AM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[3/3/2021, 10:52:02 AM] [homebridge-broadlink-rm-pro] Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at On.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at SwitchAccessory.getCharacteristicValue (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:158:5)
    at On.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1493:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1491:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at On.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:648:24)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2229:22)
[3/3/2021, 10:52:02 AM] [Broadlink RM] Projector Off getSwitchState: undefined
[3/3/2021, 10:52:02 AM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[3/3/2021, 10:52:02 AM] [homebridge-broadlink-rm-pro] Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at On.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at SwitchAccessory.getCharacteristicValue (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:158:5)
    at On.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1493:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1491:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at On.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:648:24)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2229:22)
[INFO] Adding RF Support to device 34ea34e483c3 with type 272a
```

**To Reproduce**
Start Homebridge with the following config for `homebridge-broadlink-rm`:

```
{
    "platform": "BroadlinkRM",
    "name": "Broadlink RM",
    "hideLearnButton": true,
    "hideScanFrequencyButton": true,
    "hideWelcomeMessage": true,
    "accessories": [
        {
            "type": "learn-code",
            "disableLogs": true
        },
        {
            "name": "Projector On",
            "type": "switch",
            "persistState": false,
            "disableLogs": false,
            "enableAutoOff": true,
            "onDuration": 2,
            "data": {
                "off": "",
                "on": "260084031134103511111112103511341134111211331211113412111111111210121112100002c71132133411111112103510351134111210341211113411121012111210121112100002c61233123411111112103510351134101211341112103511111112101211121012110002c61233123312111111113412331135111111341211103511111112101211121111110002c61233113412111111113411341134121111341112113411111112101211121012110002c61233113411121111113412331134111211341112113311121112101211121012110002c61233113412111012113411341233121111341112103511111112101211121111110002c61233123312111012113411341134121110351111123312111111121111111211110002c61233123312111012113412331233121111341111113511121012111210121112100002c71134103511111112103511341134111210351111113412111012111211111112100002c71134113410121112103511341332121110351012113412111012121110121112100002c71134113411111112113411341134111210351111113412111111111210121211110002c61134113411121012113411341134121111341111113412111012111210121112100002c71134113411121111113412331233121110351012113411121111111210121112110002c61134113412111012113411341233111210351111123311121111111210121211110002c61134113412111012113412331233111210351111113412111111121110121211110002c61134113412111111123311341134131011341111113412111111121110121112110002c61134113411121012123312331233121110351111123312111112101211121111110002c61332113412111111113411341233121111341111113412111111111211111112100002c71134123311121012123213331134121111341111113412111111121110121112100002c71233123311121111113214331233111211341112113312111112101211121111110002c61233123312111111113412331233121111341112113312111112101211121012110002c61233123312111012113214331135101211341211103511111211101211121012120002c51233123411111112103510351035111111341112103511111112111112111112100002c7113412331112101211341134113412111035111111341211111111121111111210000d0500000000"
            }
        },
        {
            "name": "Projector Off",
            "type": "switch",
            "persistState": false,
            "disableLogs": false,
            "enableAutoOff": true,
            "onDuration": 2,
            "data": {
                "off": "",
                "on": [
                    {
                        "data": "260084031233123312111111113412331234111111121134113411121012111210121112100002c71133123411111112103511341134111112111035113411111211101211121012110002c61233123411111112103511341035111112111035113411111112101212111111110002c61233123312111112113411341035111112111134103511111211111111121012110002c61233123312111112113312331234111112111035113410121211111111121012120002c51233123312111012113412331134121111111233123312111112101211121012110002c61134123312111111123312331233121111111134113412111111121110121211100002c71133123411121111113411341134121111111233123311121012111210121211100002c71134113411111112113411341134111112111134113411111211101211121012110002c61233113412111012113412331233121110121233113412111111121111111211110002c61134113411111211113411341332111211111134123312111012111210121112110002c51234113411111211103511341134111111121134113411111112111112111012110002c61233123312111112103412331234111111121035103510121211111111121111120002c51233123311121111113412331234111111121035113411111112111111121012120002c51233123312111111113412331233121111121034123410121211101211121012110002c61233123312111111113412331233121111111134123411111211111111121111120002c51233123312111112113312341134111111121134103511111112101211121012120002c51233123312111012113412331233111211111134123312111112101211121111110002c61233123312111012123312331233121110121134123312111012121110121112100002c71134113411111211113411341134111210121134113411121111111211111112100002c61234113411111112103510351134111111121134113411111211111111121111120002c51233123312111111123312331233121111111134123312111111121111111112100002c71134113411121012113411341233121111111233123312111111121110121112100002c71134103511111112103511341134111210121134113411121012111210121112100002c6123311341112111210341234103511111112103510351111111210121112101211000d0500000000",
                        "sendCount": 2,
                        "interval": 0.3
                    }
                ]
            }
        }
    ]
}
```

**Expected behavior**
Expect no errors in the log.

**Desktop**
- OS: MacOS 11.2.1
- Node.js: v14.15.5
- NPM: v6.14.11
- homebridge-broadlink-rm-pro v4.4.1
- homebridge: v1.3.1

**Additional context**
This started when I changed the config from a single switch with "on" and "off" behaviours to a pair of auto-off switches with "on" behaviour only.

**Comment by soulcook** [comment]
I'm getting
`[3/4/2021, 3:07:08 PM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.`
every couple of minutes. There are hundreds of them now.

**Comment by soulcook** [comment]
Any thoughts on this?

**Comment by rucanunes** [comment]
I'm still getting errors from this plugin to. Maybe because the devices are not bidirectional?

`[08/03/2021, 12:00:57] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[08/03/2021, 12:00:57] [homebridge-broadlink-rm-pro] Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at On.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at SwitchAccessory.getCharacteristicValue (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:158:5)
    at On.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1493:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1491:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at On.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:648:24)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1507:27)`

**Comment by soulcook** [comment]
To make it easier to find and fix this bug I did a run with `"debug"=true` and the `-D` flag in Homebridge, and captured this:

```
[3/8/2021, 12:56:45 PM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[3/8/2021, 12:56:45 PM] [homebridge-broadlink-rm-pro] Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at On.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at SwitchAccessory.getCharacteristicValue (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:158:5)
    at On.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1493:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1491:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at On.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:648:24)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2229:22)
[3/8/2021, 12:56:45 PM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[3/8/2021, 12:56:45 PM] [homebridge-broadlink-rm-pro] Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at On.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at SwitchAccessory.getCharacteristicValue (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:158:5)
    at On.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1493:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1491:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at On.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:648:24)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2229:22)
```
You can see that both times the error is arising from a call at line 158 of the accessory.js module.

Hope this helps.

**Comment by MsCopernic** [comment]
Same thing here ... Can any one help with this?

**Comment by tehzimd** [comment]
I believe this has been fixed in 1.3.4.. I was experiencing this issue on 1.3.3, but when I updated it seemed to resolve the issue.

**Comment by soulcook** [comment]
No, this has NOT been fixed. I’m running Homebridge 1.3.4 with homebridge-broadlink-rm 4.4.1, and the problem is still as bad as ever. 

Is there any chance of this issue getting some attention?

**Comment by MsCopernic** [comment]
> No, this has NOT been fixed. I’m running Homebridge 1.3.4 with homebridge-broadlink-rm 4.4.1, and the problem is still as bad as ever.
> 
> Is there any chance of this issue getting some attention?

It's not only not been fixed, now I have a new problem, so I had to disable the plugin: It started a loop turning on and off all my devices (TVs, amplifiers, etc). I understand that the programmer is working for free, but sincerely it would be much appreciated if he can give us a hand.

**Comment by kiwi-cam** [comment]
> now I have a new problem, so I had to disable the plugin: It started a loop turning on and off all my devices (TVs, amplifiers, etc)

@MsCopernic Could you raise a new issue for this and include your config and logs? I'm curious what's happening here.

**Comment by soulcook** [comment]
No, this has NOT been fixed. I’m running Homebridge 1.3.4 with homebridge-broadlink-rm

**Comment by soulcook** [comment]
It’s been a month since this was posted. Any chance of looking at it?

**Comment by masterfordev** [comment]
Try with the last beta: `install -g homebridge-broadlink-rm-pro@beta`

**Comment by kiwi-cam** [comment]
I'm not seeing the urgency here - isn't this a warning about potential issues in future, but everything works fine still?

**Comment by soulcook** [comment]
@kiwi-cam – So, the plan is what – to ignore the warnings, and wait until it stops working completely with a forthcoming release of Homebridge?

FWIW it’s very inconvenient having the Homebridge log swamped with hundreds of warning messages every day.

@masterfordev - Thanks! Will try the new beta and report back.

**Comment by kiwi-cam** [comment]
> @kiwi-cam – So, the plan is what – to ignore the warnings, and wait until it stops working completely with a forthcoming release of Homebridge?

Just making sure I'm understanding the issue. I'm one person with a wife, two kids, two jobs, and this as a hobby. I need to prioritise things - and they go in that order.

**Comment by kiwi-cam** [comment]
I've made some refinements to this fix and released v4.4.2-beta.6.

I'm planning for this to be the last BETA version. I will avoid making changes for about a week and, if there are no issues, I'll release 4.4.2 next week. Please test and let me know if there are any issues.

**Comment by masterfordev** [comment]
Thanks @kiwi-cam. 

You also reviewed the warning generated by the Fan? I mentioned it in #277, hope you have a chance to check it.

Im not at house to check the beta 6. Will do it later. 


```

[homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': Characteristic not in required or optional characteristic section for service Fanv2. Adding anyway.. See https://git.io/JtMGR for more info.


```

**Comment by kiwi-cam** [comment]
No, sorry. I haven't looked at the Fan specifically yet.

This change is to the "base" accessory to catch any/all undefined characteristics. It'll now default to 0 or minValue. The fan warning is about additional/unneeded characteristics.

**Comment by masterfordev** [comment]
I just saw the changes you made and I noticed that they are in the base accessory. Its ok. Anyway the fan still works, I just mention it for if you want to give a review to that warn.

**Comment by soulcook** [comment]
> > @kiwi-cam – So, the plan is what – to ignore the warnings, and wait until it stops working completely with a forthcoming release of Homebridge?
> 
> Just making sure I'm understanding the issue. I'm one person with a wife, two kids, two jobs, and this as a hobby. I need to prioritise things - and they go in that order.

@kiwi-cam Sorry – I really wasn’t complaining about you not having fixed it yet. I know you maintain this very generously in your spare time, and we all really appreciate that. Rather, I was asking about the lack of any comment on this issue after quite a long time, having noticed that many more recent issues had been discussed and some closed. I was concerned that it had somehow fallen through the cracks. 

A comment saying “sorry, no time to look at this at present” would have been fine. 

Anyway, it looks as if the latest beta has fixed the problem – so many thanks for that.
