### ISSUE TITLE
Homebridge restart: This plugin is taking long time to load

### ISSUE THREAD

**Issue by jostrasser** [kiwi-cam/homebridge-broadlink-rm#305]
Hi,

I am installing and configuring the plugin for the first time.
After installing the plugin and restarting homebridge the homebridge does not start correctly.

I cannot detect any issues in my config, I hope anybody can help.

Thanks!

errors in logs:

```
[4/23/2021, 6:45:49 AM] Loading 5 platforms...
[4/23/2021, 6:45:49 AM] [Config] Initializing config platform...
[4/23/2021, 6:45:49 AM] [Config] Spawning homebridge-config-ui-x with PID 5998
[4/23/2021, 6:45:49 AM] [Homebridge-Hue] Initializing Hue platform...
[4/23/2021, 6:45:49 AM] [Homebridge-Hue] homebridge-hue v0.13.7, node v14.16.1, homebridge v1.3.4
[4/23/2021, 6:45:49 AM] [Homebridge-Hue] config.json: nupnp: invalid key
[4/23/2021, 6:45:49 AM] [Homebridge-Hue] config.json: forceCt: invalid key
[4/23/2021, 6:45:49 AM] [eveatmo-platform] Initializing eveatmo platform...
[4/23/2021, 6:45:50 AM] [eveatmo-platform] Loading new data from API for: weatherstation
[4/23/2021, 6:45:50 AM] [eveatmo-platform] Loading new data from API for: airquality
[4/23/2021, 6:45:50 AM] [TplinkSmarthome] Initializing TplinkSmarthome platform...
[4/23/2021, 6:45:50 AM] [TplinkSmarthome] homebridge-tplink-smarthome v6.3.0, node v14.16.1, homebridge v1.3.4, api v2.7
[4/23/2021, 6:45:50 AM] [Broadlink RM] Initializing BroadlinkRM platform...
[4/23/2021, 6:45:50 AM] [Broadlink RM] [INFO] Automatic Broadlink RM device discovery has been disabled as the "hosts" option has been set.
[4/23/2021, 6:45:50 AM] [TplinkSmarthome] Configuring cached accessory: [TPLink-Wohnzimmer] UUID: x-4c6a-4dc8-910c-x deviceId: xxx
[4/23/2021, 6:45:50 AM] [TplinkSmarthome] Configuring cached accessory: [TPLink-Badezimmer] UUID: x-b96c-46f5-bab5-x deviceId: xxx
(node:5974) UnhandledPromiseRejectionWarning: AssertionError: [CONFIG ERROR] hosts should be an array of objects.: expected { Object (address, mac, ...) } to be an array
    at BroadlinkRMPlatform.discoverBroadlinkDevices (/usr/lib/node_modules/homebridge-broadlink-rm-pro/platform.js:123:12)
    at BroadlinkRMPlatform.addAccessories (/usr/lib/node_modules/homebridge-broadlink-rm-pro/platform.js:47:10)
    at BroadlinkRMPlatform.accessories (/usr/lib/node_modules/homebridge-broadlink-rm-pro/base/platform.js:28:16)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:529:24
    at new Promise (<anonymous>)
    at BridgeService.loadPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:523:12)
    at /usr/lib/node_modules/homebridge/src/server.ts:445:42
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:159:29)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5974) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[4/23/2021, 6:45:50 AM] [TplinkSmarthome] New Device Online: [TPLink-Wohnzimmer] plug [8006FED22EE15717FC3D7907C85E3F091D8084C8] 192.168.20.211 9999
[4/23/2021, 6:45:50 AM] [TplinkSmarthome] Adding: [TPLink-Wohnzimmer] plug [x]
[4/23/2021, 6:45:50 AM] [TplinkSmarthome] New Device Online: [TPLink-Badezimmer] plug [x] 192.168.20.212 9999
[4/23/2021, 6:45:50 AM] [TplinkSmarthome] Adding: [TPLink-Badezimmer] plug [x]
homebridge : TTY=pts/4 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)
[4/23/2021, 6:46:10 AM] [homebridge-broadlink-rm-pro] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.
[4/23/2021, 6:46:50 AM] [homebridge-broadlink-rm-pro] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.
[4/23/2021, 6:47:10 AM] [homebridge-broadlink-rm-pro] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.

```
config:

```
{
    "bridge": {
        "name": "HomeBridge",
        "username": "00:00:00:00:00:00",
        "port": 51826,
        "advertiser": "ciao",
        "pin": "000-00-000",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "auto",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        },
        {
            "name": "Homebridge-Hue",
            "anyOn": true,
            "lights": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": true,
            "sensors": true,
            "forceCt": true,
            "hueDimmerRepeat": false,
            "brightnessAdjustment": 100,
            "heartrate": 1,
            "timeout": 5,
            "parallelRequests": 4,
            "waitTimeResend": 100,
            "waitTimeUpdate": 20,
            "lowBattery": 25,
            "excludeSensorTypes": [
                "ZLLRelativeRotary",
                "ZLLPresence",
                "ZLLLightLevel",
                "ZLLTemperature",
                "ZHAHumidity",
                "ZHAPressure",
                "ZHAOpenClose",
                "ZHAAlarm",
                "ZHACarbonMonoxide",
                "ZHAFire",
                "ZHAVibration",
                "ZHAWater",
                "ZHAConsumption",
                "ZHAPower",
                "ZHAThermostat",
                "Daylight",
                "CLIPGenericFlag",
                "CLIPGenericStatus",
                "CLIPPresence",
                "CLIPLightLevel",
                "CLIPTemperature",
                "CLIPHumidity",
                "CLIPPressure",
                "CLIPOpenClose",
                "CLIPAlarm",
                "CLIPCarbonMonoxide",
                "CLIPFire",
                "CLIPVibration",
                "CLIPWater",
                "CLIPConsumption",
                "CLIPPower",
                "Geofence",
                "CLIP"
            ],
            "hosts": [
                "192.168.0.50"
            ],
            "users": {
                "0000000": "XXXXXXX"
            },
            "platform": "Hue"
        },
        {
            "name": "eveatmo-platform",
            "ttl": 300,
            "extra_co2_sensor": true,
            "weatherstation": true,
            "airquality": true,
            "co2_alert_threshold": 4990,
            "auth": {
                "client_id": "xxx",
                "client_secret": "xxx",
                "username": "xxx",
                "password": "xxx"
            },
            "platform": "eveatmo"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "macAddresses": [
                "00:00:00:00:00:00",
                "00:00:00:00:00:00"
            ],
            "devices": [
                {
                    "host": "192.168.20.211"
                },
                {
                    "host": "192.168.20.212"
                }
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "hosts": {
                "address": "192.168.20.180",
                "mac": "00:00:00:00:00:00",
                "isRFSupported": true,
                "isRM4": true
            },
            "platform": "BroadlinkRM"
        }
    ]
}
```

**Comment by kiwi-cam** [comment]
The hosts section needs to be an array. Just put [] around the {} to make it a single object array.
Were having issues that required the hosts section? Auto discovery should work fine in most cases.

**Comment by jostrasser** [comment]
> The hosts section needs to be an array. Just put [] around the {} to make it a single object array.
> Were having issues that required the hosts section? Auto discovery should work fine in most cases.

Hi @kiwi-cam 

Should be correct now, right?

```
{
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "hosts": [{
                "address": "192.168.20.180",
                "mac": "a0:43:b0:54:67:9f",
                "isRFSupported": true,
                "isRM4": true
            }],
            "platform": "BroadlinkRM"
}
```

I copied it from the sample, that's the reason why the host is defined.
To enable autodiscover: should I only remove the "hosts" section?
