### ISSUE TITLE
Saying TV is not a supported accessory?

### ISSUE THREAD

**Issue by TMaskell** [kiwi-cam/homebridge-broadlink-rm#32]
I am getting this message from the hombridge logs on boot

homebridge-broadlink-rm doesn't support accessories of type "TV"?

I have the the pro package installed or at least I think I do.

All other features seem to work.

03/08/2020, 15:40:44 Error: homebridge-broadlink-rm doesn't support accessories of type "TV".
    at /home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm-pro/platform.js:66:46
    at Array.forEach (<anonymous>:null:null)
    at BroadlinkRMPlatform.addAccessories (/home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm-pro/platform.js:63:24)
    at BroadlinkRMPlatform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-platform-helper/platform.js:28:10)
    at Server.loadPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:357:18)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:286:26)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
03/08/2020, 15:40:45 Got SIGTERM, shutting down Bridge...

**Comment by TMaskell** [comment]
I found the issue. type is case sensitive and needs to be tv not TV
