### ISSUE TITLE
Unhandled exception setting temperature in auto mode at air conditioner device 

### ISSUE THREAD

**Issue by xorguy** [kiwi-cam/homebridge-broadlink-rm#337]
When using the slider to set a specific temperature in automatic mode an unhandled exception is thrown and no codes are sent to the air conditioner.

**To Reproduce**
1. Click the air conditioner button at home app.
2. Set to automatic mode and then move the slider to change temperature
3. Error appears at homebridge console and no hex code is sent

**Expected behavior**
No error is thrown and hex codes are sent.

**Error thrown**
`[6/12/2021, 6:34:53 PM] [Broadlink RM] Aire Acondicionado setTargetTemperature: 25
(node:15106) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:91:40
    at catchDelayCancelError (/homebridge/node_modules/homebridge-broadlink-rm-pro/helpers/catchDelayCancelError.js:8:20)
    at AirConAccessory.performSend (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:89:11)
    at AirConAccessory.sendTemperature (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:300:18)
    at AirConAccessory.setTargetTemperature (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:189:10)
    at AirConAccessory.setCharacteristicValue (/homebridge/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:139:10)
    at TargetTemperature.emit (events.js:376:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at TargetTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at TargetTemperature.Characteristic.handleSetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:791:24)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1741:29)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
(node:15106) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 24)`

**Comment by kiwi-cam** [comment]
Can you enable debugging (`"debug": true`) and recreate this? I'd like to see what is leading up to it attempted to send an empty hexCode.

**Comment by xorguy** [comment]
Hi.

This is the log:
`[6/16/2021, 6:12:15 AM] [Broadlink RM] History Loaded from Persistant Storage
[6/16/2021, 6:12:15 AM] [Broadlink RM] ** Fakegato-storage AddWriter : Window / Door Sensor
[6/16/2021, 6:12:15 AM] [Broadlink RM] ** Fakegato-storage read FS file: /homebridge/accessories/history_00158D00042C0821.json
[6/16/2021, 6:12:15 AM] [Broadlink RM] Aire Acondicionado monitorTemperature
[6/16/2021, 6:12:15 AM] [Broadlink RM] [ERROR] Aire Acondicionado No MQTT value could be found for topic with identifier "temperature".
[6/16/2021, 6:12:15 AM] [Broadlink RM] [ERROR] Aire Acondicionado No MQTT value could be found for topic with identifier "humidity".
[6/16/2021, 6:12:15 AM] [Broadlink RM] [DEBUG] Aire Acondicionado onTemperature (0)
[6/16/2021, 6:12:17 AM] [Broadlink RM] ** Fakegato-storage write FS file: /homebridge/accessories/history_00158D00042C0821.json "firstEntry":33404,"lastEntry":37436,"usedMemory":4032,"refTime":623712121,"init
[6/16/2021, 6:12:17 AM] [Broadlink RM] Aire Acondicionado getCurrentHeatingCoolingState: 0
[6/16/2021, 6:12:17 AM] [Broadlink RM] Aire Acondicionado getTargetHeatingCoolingState: 0
[6/16/2021, 6:12:17 AM] [Broadlink RM] [ERROR] Aire Acondicionado No MQTT value could be found for topic with identifier "temperature".
[6/16/2021, 6:12:17 AM] [Broadlink RM] [ERROR] Aire Acondicionado No MQTT value could be found for topic with identifier "humidity".
[6/16/2021, 6:12:17 AM] [Broadlink RM] [DEBUG] Aire Acondicionado onTemperature (0)
[6/16/2021, 6:12:17 AM] [Broadlink RM] Aire Acondicionado getTargetTemperature: 24
[6/16/2021, 6:12:41 AM] [Broadlink RM] Aire Acondicionado getCurrentHeatingCoolingState: 0
[6/16/2021, 6:12:41 AM] [Broadlink RM] [ERROR] Aire Acondicionado No MQTT value could be found for topic with identifier "temperature".
[6/16/2021, 6:12:41 AM] [Broadlink RM] [ERROR] Aire Acondicionado No MQTT value could be found for topic with identifier "humidity".
[6/16/2021, 6:12:41 AM] [Broadlink RM] [DEBUG] Aire Acondicionado onTemperature (0)
[6/16/2021, 6:12:41 AM] [Broadlink RM] Aire Acondicionado getTargetHeatingCoolingState: 0
[6/16/2021, 6:12:41 AM] [Broadlink RM] Aire Acondicionado getTargetTemperature: 24
[6/16/2021, 6:12:50 AM] [Broadlink RM] Aire Acondicionado setTargetHeatingCoolingState: 0
[6/16/2021, 6:12:50 AM] [Broadlink RM] Aire Acondicionado sendHex (10.0.0.119; 24:df:a7:7a:cf:90) 260006016a370d0f0c0f0c290d0f0c290c0f0c100b0f0c2a0c2a0c0f0c0f0c0f0c2a0c2a0c0f0c0f0c0f0c0f0c0f0c100b100b0f0c0f0c0f0c0f0c0f0c100b2a0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c290d0e0d0f0c0e0d0e0d290d290c2a0c2a0c2a0c2a0c2a0c2a0c0f0c0f0c2a0c0f0c0f0c0f0c100b0f0c0f0c100b0f0c2a0c2a0c0f0c0f0c2a0c100b0f0c0f0c2a0c0f0c100b2a0c2a0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c100b0f0c0f0c0f0c0f0c0f0c0f0c0e0d0f0c100b0f0c0e0d0e0d0e0d0f0c0e0d0f0c0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d290d0e0d0e0d0f0c290c2a0c2a0c2a0c0f0c0f0c0f0c000d05
[6/16/2021, 6:12:50 AM] [Broadlink RM] Aire Acondicionado setCurrentHeatingCoolingState: 0
[6/16/2021, 6:12:50 AM] [Broadlink RM] Aire Acondicionado sendHex (10.0.0.119; 24:df:a7:7a:cf:90) 260076006c350c0f0c100b2a0c100b2a0c0f0c100b100b2a0c2a0c0f0c100b100b2a0c2a0c100b0f0c0f0c100b0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c290d0e0d0f0c0e0d0e0d0f0c0e0d0e0d290d0f0c0f0c0f0b100c290c100b100b100b100b100b100b2a0c0f0c2a0c2a0c2a0c2a0c2a0c2a0c000d05
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado setTargetHeatingCoolingState: 2
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado sending "on" hex before sending temperature
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado sendHex (10.0.0.119; 24:df:a7:7a:cf:90) 260006016c350f0d0e0d0e270f0d0e270f0d0d0e0d0e0e270e280e0e0d0e0d0d0e280e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e0d0e270f270f280e280e270f270f280e270f0d0e0d0e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e280e280e0d0e0d0e270f0d0e0d0e0d0e270f0d0e0d0e270f280e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e270f270f280d280e0e0d0e0d0e0d000d05
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado setTargetHeatingCoolingState: 2
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado sending "on" hex before sending temperature
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado sendHex (10.0.0.119; 24:df:a7:7a:cf:90) 260006016c350f0d0e0d0e270f0d0e270f0d0d0e0d0e0e270e280e0e0d0e0d0d0e280e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e0d0e270f270f280e280e270f270f280e270f0d0e0d0e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e280e280e0d0e0d0e270f0d0e0d0e0d0e270f0d0e0d0e270f280e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e270f270f280d280e0e0d0e0d0e0d000d05
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado sentMode (cool)
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado getCurrentHeatingCoolingState: 0
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado getTargetHeatingCoolingState: 2
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado sendHex (10.0.0.119; 24:df:a7:7a:cf:90) 260006016a370d0f0c0f0c290c100b2a0c100b100b100c290c2a0c100b100b100b2a0c2a0c100b100b100b100b100b100b100b100b100b100b100b100b100b2a0c100b100b100b100b100b100b100b2a0c100b100b100b100b2a0c2a0c2a0c2a0c2a0c2a0c2a0c2a0c0f0c0f0c2a0c0f0c0f0c100b0f0c100b100b100b100b2a0c2a0c0f0c100b2a0c0f0c0f0c0f0c2a0c0f0c0f0c2a0c2a0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c100b0f0c100b100b100b100b0f0c0f0c0f0c100b0f0c100b100b100b100b100d0d0c100b100b100d0d0e0e0b100b100d0e0b100d0d0c100d0d0c2a0e0d0e0d0e0e0d280e280c2a0c2a0e0e0d0d0c100d000d05
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado sentMode (cool)
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado getCurrentHeatingCoolingState: 0
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado getTargetHeatingCoolingState: 2
[6/16/2021, 6:12:53 AM] [Broadlink RM] Aire Acondicionado sendHex (10.0.0.119; 24:df:a7:7a:cf:90) 260006016a370d0f0c0f0c290c100b2a0c100b100b100c290c2a0c100b100b100b2a0c2a0c100b100b100b100b100b100b100b100b100b100b100b100b100b2a0c100b100b100b100b100b100b100b2a0c100b100b100b100b2a0c2a0c2a0c2a0c2a0c2a0c2a0c2a0c0f0c0f0c2a0c0f0c0f0c100b0f0c100b100b100b100b2a0c2a0c0f0c100b2a0c0f0c0f0c0f0c2a0c0f0c0f0c2a0c2a0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c100b0f0c100b100b100b100b0f0c0f0c0f0c100b0f0c100b100b100b100b100d0d0c100b100b100d0d0e0e0b100b100d0e0b100d0d0c100d0d0c2a0e0d0e0d0e0e0d280e280c2a0c2a0e0e0d0d0c100d000d05
[6/16/2021, 6:12:54 AM] [Broadlink RM] Aire Acondicionado setCurrentHeatingCoolingState: 2
[6/16/2021, 6:12:54 AM] [Broadlink RM] [DEBUG] Aire Acondicionado Potential sendTemperature (24)
[6/16/2021, 6:12:54 AM] [Broadlink RM] Aire Acondicionado getTargetTemperature: 24
(node:28016) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:91:40
    at catchDelayCancelError (/homebridge/node_modules/homebridge-broadlink-rm-pro/helpers/catchDelayCancelError.js:8:20)
    at AirConAccessory.performSend (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:89:11)
    at AirConAccessory.sendTemperature (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:300:18)
    at /homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:265:14
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:28016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[6/16/2021, 6:12:54 AM] [Broadlink RM] Aire Acondicionado setCurrentHeatingCoolingState: 2
[6/16/2021, 6:12:54 AM] [Broadlink RM] [DEBUG] Aire Acondicionado Potential sendTemperature (24)
[6/16/2021, 6:12:54 AM] [Broadlink RM] Aire Acondicionado getTargetTemperature: 24
(node:28016) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:91:40
    at catchDelayCancelError (/homebridge/node_modules/homebridge-broadlink-rm-pro/helpers/catchDelayCancelError.js:8:20)
    at AirConAccessory.performSend (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:89:11)
    at AirConAccessory.sendTemperature (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:300:18)
    at /homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:265:14
	(node:28016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[6/16/2021, 6:12:56 AM] [Broadlink RM] Aire Acondicionado setTargetTemperature: 23
[6/16/2021, 6:12:56 AM] [Broadlink RM] [DEBUG] Aire Acondicionado Potential sendTemperature (23)
[6/16/2021, 6:12:56 AM] [Broadlink RM] Aire Acondicionado getTargetTemperature: 23
(node:28016) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:91:40
    at catchDelayCancelError (/homebridge/node_modules/homebridge-broadlink-rm-pro/helpers/catchDelayCancelError.js:8:20)
    at AirConAccessory.performSend (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:89:11)
    at AirConAccessory.sendTemperature (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:300:18)
    at AirConAccessory.setTargetTemperature (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:189:10)
    at AirConAccessory.setCharacteristicValue (/homebridge/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:139:10)
    at TargetTemperature.emit (events.js:376:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at TargetTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at TargetTemperature.Characteristic.handleSetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:791:24)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1741:29)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
	(node:28016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
[6/16/2021, 6:12:58 AM] [Broadlink RM] Aire Acondicionado setTargetTemperature: 25
[6/16/2021, 6:12:58 AM] [Broadlink RM] [DEBUG] Aire Acondicionado Potential sendTemperature (25)
[6/16/2021, 6:12:58 AM] [Broadlink RM] Aire Acondicionado getTargetTemperature: 25
(node:28016) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:91:40
    at catchDelayCancelError (/homebridge/node_modules/homebridge-broadlink-rm-pro/helpers/catchDelayCancelError.js:8:20)
    at AirConAccessory.performSend (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:89:11)
    at AirConAccessory.sendTemperature (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:300:18)
    at AirConAccessory.setTargetTemperature (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:189:10)
    at AirConAccessory.setCharacteristicValue (/homebridge/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:139:10)
    at TargetTemperature.emit (events.js:376:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at TargetTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at TargetTemperature.Characteristic.handleSetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:791:24)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1741:29)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
	(node:28016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
[6/16/2021, 6:13:00 AM] [Broadlink RM] Aire Acondicionado setTargetHeatingCoolingState: 0`

My current config.json (not complete here), I have all temperatures for temperatureX,autoX,coolX and heatX:
`{
                    "name": "Aire Acondicionado",
                    "type": "air-conditioner",
                    "minTemperature": 10,
                    "maxTemperature": 30,
                    "defaultCoolTemperature": 24,
                    "defaultHeatTemperature": 25,
                    "allowResend": true,
                    "persistState": true,
                    "mqttURL": "<redacted>",
                    "mqttTopic": "<redacted>",
                    "mqttUsername": "<redacted>",
                    "mqttPassword": "<redacted>",
                    "turnOnWhenOff": true,
                    "sendTemperatureOnlyWhenOff": true,
                    "ignoreTemperatureWhenOff": true,
                    "replaceAutoMode": "cool",
                    "data": {
                        "off": [
                            {
                                "data": "260006016a370d0f0c0f0c290d0f0c290c0f0c100b0f0c2a0c2a0c0f0c0f0c0f0c2a0c2a0c0f0c0f0c0f0c0f0c0f0c100b100b0f0c0f0c0f0c0f0c0f0c100b2a0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c290d0e0d0f0c0e0d0e0d290d290c2a0c2a0c2a0c2a0c2a0c2a0c0f0c0f0c2a0c0f0c0f0c0f0c100b0f0c0f0c100b0f0c2a0c2a0c0f0c0f0c2a0c100b0f0c0f0c2a0c0f0c100b2a0c2a0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c100b0f0c0f0c0f0c0f0c0f0c0f0c0e0d0f0c100b0f0c0e0d0e0d0e0d0f0c0e0d0f0c0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d290d0e0d0e0d0f0c290c2a0c2a0c2a0c0f0c0f0c0f0c000d05",
                                "pause": 0.3
                            },
                            {
                                "data": "260076006c350c0f0c100b2a0c100b2a0c0f0c100b100b2a0c2a0c0f0c100b100b2a0c2a0c100b0f0c0f0c100b0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c290d0e0d0f0c0e0d0e0d0f0c0e0d0e0d290d0f0c0f0c0f0b100c290c100b100b100b100b100b100b2a0c0f0c2a0c2a0c2a0c2a0c2a0c2a0c000d05"
                            }
                        ],
                        "on": [
                            {
                                "data": "260006016c350f0d0e0d0e270f0d0e270f0d0d0e0d0e0e270e280e0e0d0e0d0d0e280e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e0d0e270f270f280e280e270f270f280e270f0d0e0d0e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e280e280e0d0e0d0e270f0d0e0d0e0d0e270f0d0e0d0e270f280e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e270f270f280d280e0e0d0e0d0e0d000d05",
                                "pause": 0.3
                            },
                            {
                                "data": "260006016a370d0f0c0f0c290c100b2a0c100b100b100c290c2a0c100b100b100b2a0c2a0c100b100b100b100b100b100b100b100b100b100b100b100b100b2a0c100b100b100b100b100b100b100b2a0c100b100b100b100b2a0c2a0c2a0c2a0c2a0c2a0c2a0c2a0c0f0c0f0c2a0c0f0c0f0c100b0f0c100b100b100b100b2a0c2a0c0f0c100b2a0c0f0c0f0c0f0c2a0c0f0c0f0c2a0c2a0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c100b0f0c100b100b100b100b0f0c0f0c0f0c100b0f0c100b100b100b100b100d0d0c100b100b100d0d0e0e0b100b100d0e0b100d0d0c100d0d0c2a0e0d0e0d0e0e0d280e280c2a0c2a0e0e0d0d0c100d000d05"
                            }
                        ],
                        "auto30": [
                            {
                                "data": "260006016d350e0e0d0e0d280e0e0d280e0e0d0e0d0e0d280e280e0e0d0e0d0e0d280e280e0e0d0e0d0e0d0e0d0e0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e0d0e270f270f270f270f270f270f270f270f0d0e0d0e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e280e270f270f0d0e0d0e0d0e0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e0d0e0d0e0d0e280e0d0e280e280e000d05",
                                "pause": 0.3
                            },
                            {
                                "data": "260006016a370d0f0c0e0d290d0e0d290d0f0c0f0c0f0c290d290d0f0c0f0c0f0c290d290d0e0d0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c290d0f0c0f0c0f0c0f0c0f0c0f0c100b2a0c100b100b100b100b2a0c2a0c2a0c2a0c2a0c2a0c2a0c2a0c100b100b2a0c100b100b100b100b0f0c100b100b0f0c2a0c2a0c100b100b100b100b100b100b100b2a0c2a0c2a0c100b100b100b100b100b100b100b100b100b100b100b100b100b100b100b100c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c0f0c100b100b100b100b100b2a0c100b100b100b100b100b100b2a0c100b2a0c2a0c000d05"
                            }
                        ],`

**Comment by kiwi-cam** [comment]
Looks like the error is happening when it's trying to send the code for `cool24`. Could you check you've got `data` defined for `cool24`?

**Comment by xorguy** [comment]
I think it first sends the cool24 because it is set as the defaultcooltemperature. What I have as cool24 is the same as the others but with the correct hex codes to be sent, it sends two hex codes, with a pause between them:
`"cool24": [
                            {
                                "data": "260006016d340f0d0e0d0e280e0d0e270f0d0e0d0e0d0e270f270f0d0e0d0e0d0e280e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e0d0e0d0e270f270f270f270f270f270f270f270f0d0e0d0e270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f270f0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0e0d280e280e0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e270f0d0e0d0e270f270f270f270f0d0e270f0d0e0d0e000d05",
                                "pause": 0.3
                            },
                            {
                                "data": "260006016b360e0d0e0d0e280e0d0d290d0e0d0e0e0d0e280d290c0f0e0d0d0e0d290d290d0e0d0e0d0e0d0e0c0f0d0e0d0e0c0f0d0e0d0e0d0e0d0e0d0e0c2a0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d290d0e0d0e0d0e0d0e0c290e280e280d290d290d290d290d290d0e0d0e0d290d0e0d0e0c0f0d0e0d0e0d0e0d0e0d0e0d290d290d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d0e0d290d280e0e0d0e0d0e0c0e0e0d0e0d0e0e0d0d0e0d0e0d0e0e0d0d0e0d0e0d0e0d0d0e0e0d0e0d0d0e0d0e0e0d0e0d0e0d0e0d0d0e0e0d0e0d0d0e0d0e0d0e0e0d0d0e0d0e0d0e0d0e0d0e0d0e0d0e0e0d0d0e0d0e0d0e0d0e0d0e0d290d0e0c0f0d290d290c2a0d290d0e0d290d0e0d0e0d000d05"
                            }
                        ],`
