### ISSUE TITLE
Air conditioner speed and oscillate support

### ISSUE THREAD

**Issue by NikDevx** [kiwi-cam/homebridge-broadlink-rm#339]
Hello 👋🏻 
Thanks for the plugin!

Can you add support for these two features?
AC speed and oscillate

![](https://user-images.githubusercontent.com/9190080/56595083-94073e00-6620-11e9-9aa3-bc69732acfc0.png)

**Comment by kiwi-cam** [comment]
The Aircon accessory is based on the HomeKit Thermostat which doesn't support these attributes. Check out the Heater-Cooler accessory - it should do what you're after.

**Comment by NikDevx** [comment]
Thanks a lot!

**Comment by NikDevx** [comment]
I have a some error

```
[15.06.2021, 18:02:23] [Broadlink RM] Example Heater Cooler setRotationSpeed: 0
[15.06.2021, 18:02:23] [Broadlink RM] Example Heater Cooler setActive: 1
[15.06.2021, 18:02:23] [Broadlink RM] Looking up temperature hex codes for 16
[15.06.2021, 18:02:23] [Broadlink RM] Hex codes not found for rotationSpeed
[15.06.2021, 18:02:23] [Broadlink RM] Hex codes not found for swingMode
[15.06.2021, 18:02:23] [Broadlink RM]   Sending hex codes for temperature 16
(node:1905) UnhandledPromiseRejectionWarning: ReferenceError: name is not defined
    at HeaterCoolerAccessory.setRotationSpeed (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/heater-cooler.js:488:30)
    at HeaterCoolerAccessory.setCharacteristicValue (/usr/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:139:10)
    at RotationSpeed.emit (events.js:376:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at RotationSpeed.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:1905) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 26)
[15.06.2021, 18:02:54] [homebridge-cmdswitch2] Failed to determine PlayStation 5 state.
[15.06.2021, 18:02:54] [homebridge-cmdswitch2] Error: Unable to locate device: device with id 78C881B63FE1
    at PendingDevice.<anonymous> (/usr/lib/node_modules/playactor/dist/device/pending.js:82:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/playactor/dist/device/pending.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

[15.06.2021, 18:03:23] [Broadlink RM] Example Heater Cooler setRotationSpeed: 25
[15.06.2021, 18:03:23] [Broadlink RM] Example Heater Cooler setActive: 1

```[15.06.2021, 18:03:23] [Broadlink RM] Looking up temperature hex codes for 16
[15.06.2021, 18:03:23] [Broadlink RM]   Sending hex codes for temperature 16
[15.06.2021, 18:03:23] [Broadlink RM] Example Heater Cooler sendHex (192.168.0.33; a0:43:b0:31:9b:c2) 2600d800000126911435143514111311141014101436133614351435143614101410141113361410141014111311141014101435143614351410141113111410141014111311131114101410141113111410143514111336141014101411131114101410141014111311141014101411131114351410141113111410141014101411131114101410141113111410141014101411131114101410141113111410141014361311141014101410141113111410141014111311143514101411131114101410141014111336143514111336141014101435143614000d050000000000000000000000000000
(node:1905) UnhandledPromiseRejectionWarning: ReferenceError: name is not defined
    at HeaterCoolerAccessory.setRotationSpeed (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/heater-cooler.js:488:30)
    at HeaterCoolerAccessory.setCharacteristicValue (/usr/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:139:10)
    at RotationSpeed.emit (events.js:376:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at RotationSpeed.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:1905) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 27)
[15.06.2021, 18:03:32] [Broadlink RM] Example Heater Cooler setRotationSpeed: 50
[15.06.2021, 18:03:32] [Broadlink RM] Example Heater Cooler setActive: 1
[15.06.2021, 18:03:32] [Broadlink RM] Looking up temperature hex codes for 16
[15.06.2021, 18:03:32] [Broadlink RM]   Sending hex codes for temperature 16
[15.06.2021, 18:03:32] [Broadlink RM] Example Heater Cooler sendHex (192.168.0.33; a0:43:b0:31:9b:c2) 2600d8000001269114351436141014101410141113361435143515351435141014111410143514101411141014101410141113361435143514111410141014101411131114101410141014111410150f1410143614351410141014111410141014101411131114101410141014111410141014351411141014101410141113111410141014111311141014101410141113111410141014111311141014101410141113361410141014111410141014101411131114101410141014111435141014101411141014101410143614351435141113111410143514000d050000000000000000000000000000
(node:1905) UnhandledPromiseRejectionWarning: ReferenceError: name is not defined
    at HeaterCoolerAccessory.setRotationSpeed (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/heater-cooler.js:488:30)
    at HeaterCoolerAccessory.setCharacteristicValue (/usr/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:139:10)
    at RotationSpeed.emit (events.js:376:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at RotationSpeed.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:1905) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 28)
[15.06.2021, 18:03:36] [Broadlink RM] Example Heater Cooler setRotationSpeed: 75
[15.06.2021, 18:03:36] [Broadlink RM] Example Heater Cooler setActive: 1
[15.06.2021, 18:03:36] [Broadlink RM] Looking up temperature hex codes for 16
[15.06.2021, 18:03:36] [Broadlink RM]   Sending hex codes for temperature 16
[15.06.2021, 18:03:36] [Broadlink RM] Example Heater Cooler sendHex (192.168.0.33; a0:43:b0:31:9b:c2) 2600d800000125921337133614101410141113111435143514361435143514111410141014351411141014101410141113111435143514361410141014101411141014101410141113111410141014101411141014351410141114101410141014111311141014101410141114101410141014361410141014101411131114101410141113111410141014101411131114101410141014111410141014101411131114351410141113111410141014101411141014101410141113111435141014111311141014101410143614351435141114351435141113000d050000000000000000000000000000
(node:1905) UnhandledPromiseRejectionWarning: ReferenceError: name is not defined
    at HeaterCoolerAccessory.setRotationSpeed (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/heater-cooler.js:488:30)
    at HeaterCoolerAccessory.setCharacteristicValue (/usr/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:139:10)
    at RotationSpeed.emit (events.js:376:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at RotationSpeed.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:1905) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 29)
[15.06.2021, 18:03:42] [Broadlink RM] Example Heater Cooler setRotationSpeed: 100
[15.06.2021, 18:03:42] [Broadlink RM] Example Heater Cooler setActive: 1
[15.06.2021, 18:03:42] [Broadlink RM] Looking up temperature hex codes for 16
[15.06.2021, 18:03:42] [Broadlink RM]   Sending hex codes for temperature 16
[15.06.2021, 18:03:42] [Broadlink RM] Example Heater Cooler sendHex (192.168.0.33; a0:43:b0:31:9b:c2) 2600d800000124931337123713111312121213111336133712371336133713111410141014361311141014101411131114101435143613361410141014111311141014101411131114101410141014111311143514101411131114101410141113111410141013111412121114101410141113361410141013121311141014101312131113111311131114111311141013111312121213111410141013121311131113361411131113111410131212121311131113121212131114101336141113111410141014111212133614351436131114101436131114000d050000000000000000000000000000
(node:1905) UnhandledPromiseRejectionWarning: ReferenceError: name is not defined
    at HeaterCoolerAccessory.setRotationSpeed (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/heater-cooler.js:488:30)
    at HeaterCoolerAccessory.setCharacteristicValue (/usr/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:139:10)
    at RotationSpeed.emit (events.js:376:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at RotationSpeed.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:1905) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 30)
```


My config

```
{
    "name": "Example Heater Cooler",
    "type": "heater-cooler",
    "minTemperature": 16,
    "maxTemperature": 30,
    "tempStepSize": 1,
    "fanStepSize": 25,
    "noHumidity": true,
    "temperatureUpdateFrequency": 60,
    "address": "192.168.0.33",
    "host": "A0:43:b0:31:9b:c2",
    "data": {
        "heat": {
            "on": "ON_HEX_CODE",
            "off": "2600d800000124931237123811131212121311131138123712381138123712371238111312371213111311131212121212131138123712381113111312121212121311131113121212121213111312121212123811381212121212131113111312121213111311131212121212131113111312371213111311131212121212131113121212121212121311131113121212131113111312121212121311131113121212121213111311131212121212131113121212121213113812121237121311131113121212121238113812371213111311131212123712000d050000000000000000000000000000",
            "temperatureCodes": {
                "16": {
                    "rotationSpeed25": {
                        "swingDnd": "2600d800000126911336143514111311141014101436133614351436133614101410143613361410141113111311141014101436133614351411131113111410141113111311141014101411131114101410143613111336141014111311131114101410141113111410141014111311131114351411131113111410141014111311141014101411131113111410141113111311141014101411131113111410141014361311141014101411131114101410141113111311150f14101436131114101410141113111410143514361336141014361336143514000d050000000000000000000000000000",
                        "swingOn": "2600d800000123941138103911131114101410141138113910391138113910141113113910391014111311141014101411131139103910391113111410141014111311141014101411131113111410141014113811141039111311131114101410141113111410141014111311391014101411381114101410141113111311141014101411131114101410141113111311141014101411131114101410141113111410391014111311141014101411131113111410141014113811391014113811131114101411131138111410141039123811381039113910000d050000000000000000000000000000",
                        "swingOff": "2600d800000123941138113910141014111311131139103911381139103911131114103910391113111410141014111311131139103911381114101410141113111410141014111311131114101411131113113910141138111311141014101411131114101410141113111311141014111311381114101411131113111410141014111311131114101411131113111410141014111311141014101411131113111410391113111311141014101411131114101410141113113910391014113811141014101411131139101410391113113910391138113910000d050000000000000000000000000000"
                    },
                    "rotationSpeed50": {
                        "swingDnd": "2600d800000126911436143514101410141114101435143514361435143514111410143514351411141014101410141113111435143514361410141014101411141014101410141014111410141014101411133614351410141114101410141014111311141014101410141114101410141014361311141014101410141114101410141014111311141014101410141114101410141014111311141014101410141113361410141014111311141014101411131114101410141014111336141014101411131114101410143514361435141014361410143514000d050000000000000000000000000000",
                        "swingOn": "2600d800000123941138103911131114101410141138113910391138113910141113113910391014111311141014101411131139103910391113111410141014111311141014101411131113111410141014113811141039111311131114101410141113111410141014111311391014101411381114101410141113111311141014101411131114101410141113111311141014101411131114101410141113111410391014111311141014101411131113111410141014113811391014113811131114101411131138111410141039123811381039113910000d050000000000000000000000000000",
                        "swingOff": "2600d800000123941138113910141014111311131139103911381139103911131114103910391113111410141014111311131139103911381114101410141113111410141014111311131114101411131113113910141138111311141014101411131114101410141113111311141014111311381114101411131113111410141014111311131114101411131113111410141014111311141014101411131113111410391113111311141014101411131114101410141113113910391014113811141014101411131139101410391113113910391138113910000d050000000000000000000000000000"
                    },
                    "rotationSpeed75": {
                        "swingDnd": "2600d800000123931238113812121212121311131336123712381237123712131113123712381113111312121212121311131237123811381212121212121213131112121212121311131113121212121213111312371212121311131212121212131113111312121212121311131212121212381113121212121213111311131212121212131113121212121212121311131212121212131113111312121212121311381212121212131113121212121213111311131212121212131138121212121213111312121212123811381237121212131113123712000d050000000000000000000000000000",
                        "swingOn": "2600d800000123941138103911131114101410141138113910391138113910141113113910391014111311141014101411131139103910391113111410141014111311141014101411131113111410141014113811141039111311131114101410141113111410141014111311391014101411381114101410141113111311141014101411131114101410141113111311141014101411131114101410141113111410391014111311141014101411131113111410141014113811391014113811131114101411131138111410141039123811381039113910000d050000000000000000000000000000",
                        "swingOff": "2600d800000123941138113910141014111311131139103911381139103911131114103910391113111410141014111311131139103911381114101410141113111410141014111311131114101411131113113910141138111311141014101411131114101410141113111311141014111311381114101411131113111410141014111311131114101411131113111410141014111311141014101411131113111410391113111311141014101411131114101410141113113910391014113811141014101411131139101410391113113910391138113910000d050000000000000000000000000000"
                    },
                    "rotationSpeed100": {
                        "swingDnd": "2600d800000125911436133614101411131113111435143613361435143514111410143514361311141014101411131113111435143613361410141014111311141014101410141113111410141014111311133614101411131114101410141014111311141014101411131113111410141014361311141014101411131114101410141113111311141014101411131114101410141113111311141014101411131114351410141113111410141014111311141014101410141113111435141014111311141014101411133614351435141114351435141113000d050000000000000000000000000000",
                        "swingOn": "2600d800000123941138103911131114101410141138113910391138113910141113113910391014111311141014101411131139103910391113111410141014111311141014101411131113111410141014113811141039111311131114101410141113111410141014111311391014101411381114101410141113111311141014101411131114101410141113111311141014101411131114101410141113111410391014111311141014101411131113111410141014113811391014113811131114101411131138111410141039123811381039113910000d050000000000000000000000000000",
                        "swingOff": "2600d800000123941138113910141014111311131139103911381139103911131114103910391113111410141014111311131139103911381114101410141113111410141014111311131114101411131113113910141138111311141014101411131114101410141113111311141014111311381114101411131113111410141014111311131114101411131113111410141014111311141014101411131113111410391113111311141014101411131114101410141113113910391014113811141014101411131139101410391113113910391138113910000d050000000000000000000000000000"
                    }
                }
            },
            "cool": {
                "on": "ON_HEX_CODE",
                "off": "2600d800000124931237123811131212121311131138123712381138123712371238111312371213111311131212121212131138123712381113111312121212121311131113121212121213111312121212123811381212121212131113111312121213111311131212121212131113111312371213111311131212121212131113121212121212121311131113121212131113111312121212121311131113121212121213111311131212121212131113121212121213113812121237121311131113121212121238113812371213111311131212123712000d050000000000000000000000000000",
                "temperatureCodes": {
                    "16": {
                        "rotationSpeed25": {
                            "swingDnd": "2600d800000126911435143514111311141014101436133614351435143614101410141113361410141014111311141014101435143614351410141113111410141014111311131114101410141113111410143514111336141014101411131114101410141014111311141014101411131114351410141113111410141014101411131114101410141113111410141014101411131114101410141113111410141014361311141014101410141113111410141014111311143514101411131114101410141014111336143514111336141014101435143614000d050000000000000000000000000000",
                            "swingOn": "2600d800000123941138103911131114101410141138113910391138113910141113113910391014111311141014101411131139103910391113111410141014111311141014101411131113111410141014113811141039111311131114101410141113111410141014111311391014101411381114101410141113111311141014101411131114101410141113111311141014101411131114101410141113111410391014111311141014101411131113111410141014113811391014113811131114101411131138111410141039123811381039113910000d050000000000000000000000000000",
                            "swingOff": "2600d800000123941138113910141014111311131139103911381139103911131114103910391113111410141014111311131139103911381114101410141113111410141014111311131114101411131113113910141138111311141014101411131114101410141113111311141014111311381114101411131113111410141014111311131114101411131113111410141014111311141014101411131113111410391113111311141014101411131114101410141113113910391014113811141014101411131139101410391113113910391138113910000d050000000000000000000000000000"
                        },
                        "rotationSpeed50": {
                            "swingDnd": "2600d8000001269114351436141014101410141113361435143515351435141014111410143514101411141014101410141113361435143514111410141014101411131114101410141014111410150f1410143614351410141014111410141014101411131114101410141014111410141014351411141014101410141113111410141014111311141014101410141113111410141014111311141014101410141113361410141014111410141014101411131114101410141014111435141014101411141014101410143614351435141113111410143514000d050000000000000000000000000000",
                            "swingOn": "2600d800000123941138103911131114101410141138113910391138113910141113113910391014111311141014101411131139103910391113111410141014111311141014101411131113111410141014113811141039111311131114101410141113111410141014111311391014101411381114101410141113111311141014101411131114101410141113111311141014101411131114101410141113111410391014111311141014101411131113111410141014113811391014113811131114101411131138111410141039123811381039113910000d050000000000000000000000000000",
                            "swingOff": "2600d800000123941138113910141014111311131139103911381139103911131114103910391113111410141014111311131139103911381114101410141113111410141014111311131114101411131113113910141138111311141014101411131114101410141113111311141014111311381114101411131113111410141014111311131114101411131113111410141014111311141014101411131113111410391113111311141014101411131114101410141113113910391014113811141014101411131139101410391113113910391138113910000d050000000000000000000000000000"
                        },
                        "rotationSpeed75": {
                            "swingDnd": "2600d800000125921337133614101410141113111435143514361435143514111410141014351411141014101410141113111435143514361410141014101411141014101410141113111410141014101411141014351410141114101410141014111311141014101410141114101410141014361410141014101411131114101410141113111410141014101411131114101410141014111410141014101411131114351410141113111410141014101411141014101410141113111435141014111311141014101410143614351435141114351435141113000d050000000000000000000000000000",
                            "swingOn": "2600d800000123941138103911131114101410141138113910391138113910141113113910391014111311141014101411131139103910391113111410141014111311141014101411131113111410141014113811141039111311131114101410141113111410141014111311391014101411381114101410141113111311141014101411131114101410141113111311141014101411131114101410141113111410391014111311141014101411131113111410141014113811391014113811131114101411131138111410141039123811381039113910000d050000000000000000000000000000",
                            "swingOff": "2600d800000123941138113910141014111311131139103911381139103911131114103910391113111410141014111311131139103911381114101410141113111410141014111311131114101411131113113910141138111311141014101411131114101410141113111311141014111311381114101411131113111410141014111311131114101411131113111410141014111311141014101411131113111410391113111311141014101411131114101410141113113910391014113811141014101411131139101410391113113910391138113910000d050000000000000000000000000000"
                        },
                        "rotationSpeed100": {
                            "swingDnd": "2600d800000124931337123713111312121213111336133712371336133713111410141014361311141014101411131114101435143613361410141014111311141014101411131114101410141014111311143514101411131114101410141113111410141013111412121114101410141113361410141013121311141014101312131113111311131114111311141013111312121213111410141013121311131113361411131113111410131212121311131113121212131114101336141113111410141014111212133614351436131114101436131114000d050000000000000000000000000000",
                            "swingOn": "2600d800000123941138103911131114101410141138113910391138113910141113113910391014111311141014101411131139103910391113111410141014111311141014101411131113111410141014113811141039111311131114101410141113111410141014111311391014101411381114101410141113111311141014101411131114101410141113111311141014101411131114101410141113111410391014111311141014101411131113111410141014113811391014113811131114101411131138111410141039123811381039113910000d050000000000000000000000000000",
                            "swingOff": "2600d800000123941138113910141014111311131139103911381139103911131114103910391113111410141014111311131139103911381114101410141113111410141014111311131114101411131113113910141138111311141014101411131114101410141113111311141014111311381114101411131113111410141014111311131114101411131113111410141014111311141014101411131113111410391113111311141014101411131114101410141113113910391014113811141014101411131139101410391113113910391138113910000d050000000000000000000000000000"
                        }
                    }
                }
            }
        }
    },

```

**Comment by kiwi-cam** [comment]
This issue should be fixed in the latest beta: v4.4.5-beta.0. Let me know how you get on.

**Comment by uzumaki20398** [comment]
"swingDnd":"HEX_CODE", "swingToggle":"HEX_CODE"

or

"swingOn":"HEX_CODE",
"swingOff":"HEX_CODE"

"swingDnd" has to be used with "swingToggle".
"swingOn" has to be used with "swingOff".

**Comment by kiwi-cam** [comment]
Good catch @uzumaki20398. 

@NikDevx There's more documentation on the heater-cooler here which might help if you haven't seen it: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/docs/heater-cooler.md, along with the rest here: https://broadlink.kiwicam.nz/#heatercooler

EDIT - but the error in your logs was a bug which should be sorted in the current BETA and next version.

**Comment by NikDevx** [comment]
> Good catch @uzumaki20398.
> 
> @NikDevx There's more documentation on the heater-cooler here which might help if you haven't seen it: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/docs/heater-cooler.md, along with the rest here: https://broadlink.kiwicam.nz/#heatercooler
> 
> EDIT - but the error in your logs was a bug which should be sorted in the current BETA and next version.

In beta, the error logs have been fixed. Thank you.

**Comment by NikDevx** [comment]
> "swingDnd":"HEX_CODE", "swingToggle":"HEX_CODE"
> 
> or
> 
> "swingOn":"HEX_CODE",
> "swingOff":"HEX_CODE"
> 
> "swingDnd" has to be used with "swingToggle".
> "swingOn" has to be used with "swingOff".

Thanks.
Everything works for me together

```
"swingDnd"
"swingOn"
"swingOff"
```
