### ISSUE TITLE
AirConditioner - ReferenceError: logLevel is not defined

### ISSUE THREAD

**Issue by unickq** [kiwi-cam/homebridge-broadlink-rm#341]
**Describe the bug**
```
[homebridge-broadlink-rm-pro] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.
```
```
(node:8901) UnhandledPromiseRejectionWarning: ReferenceError: logLevel is not defined
    at AirConAccessory.updateAccessories (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:160:5)
    at /homebridge/node_modules/homebridge-broadlink-rm-pro/base/platform.js:79:50
    at Array.forEach (<anonymous>)
    at BroadlinkRMPlatform.accessories (/homebridge/node_modules/homebridge-broadlink-rm-pro/base/platform.js:78:17)
```

**To Reproduce**
```
 "accessories": [
                {
                    "name": "Air Conditioner",
                    "type": "air-conditioner",
                    "autoSwitch": "A/C Auto Switch",
                    "minTemperature": 17,
                    "maxTemperature": 30,
                    "temperatureFilePath": "/homebridge/temp",
                    "pseudoDeviceTemperature": 23,
                    "defaultCoolTemperature": 17,
                    "defaultHeatTemperature": 23,
                    "autoHeatTemperature": 23,
                    "autoCoolTemperature": 17,
                    "data": {...}
                },
```

homebridge-broadlink-rm-pro v4.4.4

**Comment by kiwi-cam** [comment]
Thanks for the report @unickq.

The first error you show is being addressed in #335. The other one is a bug. I've just pushed a new BETA (4.4.5-beta.1) which should fix this error. Let me know how you get on.

**Comment by unickq** [comment]
@kiwi-cam thank's for the fix. 
Installed 4.4.5-beta1, it loaded pretty slow but looks as it works. Btw do you know what is this warning about?

```[6/17/2021, 4:01:46 PM] Homebridge v1.3.4 (ds218+) is running on port 53824.
[6/17/2021, 4:01:46 PM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[6/17/2021, 4:01:46 PM] [Broadlink RM] [INFO] Discovered Broadlink RM3 Mini (2737) at 10.0.0.61 (c8:f7:42:40:8c:fc)
[6/17/2021, 4:01:47 PM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
wakeUntilAPIReady: try 10
wakeUntilAPIReady: try 20
[6/17/2021, 4:03:02 PM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
wakeUntilAPIReady: try 30
```

**Comment by kiwi-cam** [comment]
Yeah, you're using "pseudoDeviceTemperature" which won't have a Humidity value but it's trying to set one. The next BETA will sort this.
