### ISSUE TITLE
This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: logLevel is not defined.

### ISSUE THREAD

**Issue by joshuachung** [kiwi-cam/homebridge-broadlink-rm#343]
Temperature **is shown** in Homebridge accessories but error in HomeKit

Below is the log:

```
[6/17/2021, 8:51:24 PM] [Broadlink RM] 
[6/17/2021, 8:51:24 PM] [Broadlink RM] **************************************************************************************************************
[6/17/2021, 8:51:24 PM] [Broadlink RM] ** Welcome to version 4.4.4 of the Homebridge Broadlink RM Plugin!
[6/17/2021, 8:51:24 PM] [Broadlink RM] ** 
[6/17/2021, 8:51:24 PM] [Broadlink RM] ** Find out what's in the latest release here: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/CHANGELOG.md
[6/17/2021, 8:51:24 PM] [Broadlink RM] ** 
[6/17/2021, 8:51:24 PM] [Broadlink RM] ** If you like this plugin then please star it on GitHub or better yet
[6/17/2021, 8:51:24 PM] [Broadlink RM] ** buy me a drink using Paypal https://paypal.me/kiwicamRM.
[6/17/2021, 8:51:24 PM] [Broadlink RM] **
[6/17/2021, 8:51:24 PM] [Broadlink RM] ** You can disable this message by adding "hideWelcomeMessage": true to the config (see config-sample.json).
[6/17/2021, 8:51:24 PM] [Broadlink RM] **
[6/17/2021, 8:51:24 PM] [Broadlink RM] **************************************************************************************************************
[6/17/2021, 8:51:24 PM] [Broadlink RM] 
[6/17/2021, 8:51:25 PM] [homebridge-broadlink-rm-pro] This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: logLevel is not defined. See https://git.io/JtMGR for more info.
[6/17/2021, 8:51:25 PM] [homebridge-broadlink-rm-pro] ReferenceError: logLevel is not defined
    at TemperatureSensorAccessory.mqttValueForIdentifier (/homebridge/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:372:37)
    at TemperatureSensorAccessory.addTemperatureCallbackToQueue (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:459:32)
    at TemperatureSensorAccessory.getCurrentTemperature (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:584:10)
    at CurrentTemperature.emit (events.js:376:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at CurrentTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
[6/17/2021, 8:51:25 PM] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[6/17/2021, 8:51:25 PM] [homebridge-broadlink-rm-pro] Error: 
    at BatteryLevel.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at BatteryLevel.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at TemperatureSensorAccessory.getBatteryLevel (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/temperatureSensor.js:56:5)
    at BatteryLevel.emit (events.js:376:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at BatteryLevel.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
[6/17/2021, 8:51:25 PM] [Broadlink RM] **Fakegato-timer: addData  LivingRoom Humidity { time: 1623934285, humidity: 67.86 }  immediate:  false
[6/17/2021, 8:51:25 PM] [Broadlink RM] **Fakegato-timer: addData  LivingRoom temperature { time: 1623934285, temp: 27.57, humidity: 67.86 }  immediate:  false
[6/17/2021, 8:51:28 PM] [homebridge-broadlink-rm-pro] This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: logLevel is not defined. See https://git.io/JtMGR for more info.
[6/17/2021, 8:51:28 PM] [homebridge-broadlink-rm-pro] ReferenceError: logLevel is not defined
    at TemperatureSensorAccessory.mqttValueForIdentifier (/homebridge/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:372:37)
    at TemperatureSensorAccessory.addTemperatureCallbackToQueue (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:459:32)
    at TemperatureSensorAccessory.getCurrentTemperature (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:584:10)
    at CurrentTemperature.emit (events.js:376:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at CurrentTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
[6/17/2021, 8:51:28 PM] [Broadlink RM] **Fakegato-timer: addData  LivingRoom Humidity { time: 1623934289, humidity: 68.53 }  immediate:  false
[6/17/2021, 8:51:28 PM] [Broadlink RM] **Fakegato-timer: addData  LivingRoom temperature { time: 1623934289, temp: 27.49, humidity: 68.53 }  immediate:  false
[6/17/2021, 8:51:34 PM] [Broadlink RM] **Fakegato-timer: addData  LivingRoom Humidity { time: 1623934294, humidity: 68.53 }  immediate:  false
[6/17/2021, 8:51:34 PM] [homebridge-broadlink-rm-pro] This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: logLevel is not defined. See https://git.io/JtMGR for more info.
[6/17/2021, 8:51:34 PM] [homebridge-broadlink-rm-pro] ReferenceError: logLevel is not defined
    at TemperatureSensorAccessory.mqttValueForIdentifier (/homebridge/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:372:37)
    at TemperatureSensorAccessory.addTemperatureCallbackToQueue (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:459:32)
    at TemperatureSensorAccessory.getCurrentTemperature (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:584:10)
    at CurrentTemperature.emit (events.js:376:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at CurrentTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
[6/17/2021, 8:51:44 PM] [Broadlink RM] **Fakegato-timer: addData  LivingRoom Humidity { time: 1623934304, humidity: 68.53 }  immediate:  false
[6/17/2021, 8:51:44 PM] [Broadlink RM] **Fakegato-timer: addData  LivingRoom temperature { time: 1623934304, temp: 27.49, humidity: 68.53 }  immediate:  false
```

Here is the config:

```
 "platforms": [
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "loglevel": 0,
            "hosts": [
                {
                    "address": "IPv4",
                    "mac": "MAC_address",
                    "isRFSupported": true,
                    "isRM4": true
                }
            ],
            "accessories": [
                {
                    "name": "LivingRoom Humidity",
                    "type": "humiditySensor"
                },
                {
                    "name": "LivingRoom temperature",
                    "type": "temperatureSensor",
                    "batteryAlerts": true,
                    "mqttURL": "mqtt://IPv4",
                    "mqttTopic": [
                        {
                            "identifier": "temperature",
                            "topic": "/mi_temp/LivingRoom/temperature"
                        },
                        {
                            "identifier": "humidity",
                            "topic": "/mi_temp/LivingRoom/humidity"
                        }
                    ]
                }
            ]
        },
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        }
    ]

```

**Comment by kiwi-cam** [comment]
This should be fixed in the new BETA. Let me know how it goes.
