### ISSUE TITLE
homebridge console keep have error pop out

### ISSUE THREAD

**Issue by hamwong** [kiwi-cam/homebridge-broadlink-rm#378]
(node:12886) UnhandledPromiseRejectionWarning: TypeError: this.isAutoSwitchOn is not a function
    at HeaterCoolerAccessory.checkTemperatureForAutoOnOff (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/heater-cooler.js:763:15)
    at HeaterCoolerAccessory.processQueuedTemperatureCallbacks (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/heater-cooler.js:720:10)
    at HeaterCoolerAccessory.onTemperature (/homebridge/node_modules/homebridge-broadlink-rm-pro/accessories/heater-cooler.js:581:10)
    at Device.emit (events.js:400:28)
    at Device.onPayloadReceived (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/kiwicam-broadlinkjs-rm/index.js:458:14)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/kiwicam-broadlinkjs-rm/index.js:343:14)
    at Socket.emit (events.js:400:28)
    at UDP.onMessage (dgram.js:941:8)
(node:12886) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 75)

**Comment by hamwong** [comment]
```
,
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": true,
            "hideLearnButton": true,
            "hideWelcomeMessage": false,
            "hosts": [
                {
                    "address": "xxx.xxx.xxx.xxx",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "isRFSupported": true
                }
            ],
            "accessories": [
                {
                    "name": "Carrier",
                    "type": "heater-cooler",
                    "temperatureUnits": "c",
                    "minTemperature": 17,
                    "maxTemperature": 25,
                    "tempStepSize": 1,
                    "turnOnWhenOff": true,
                    "coolOnly": true,
                    "noHumidity": true,
                    "coolingThresholdTemperature": 17,
                    "autoCoolTemperature": 24,
                    "defaultRotationSpeed": 99,
                    "fanStepSize": 33,
                    "data": {
                        "cool": {
                            "on": "2600d8000001158c112f1114112d132e11131111142c122f11121212112e122f1113122e1212112f112e1312112e12111212132e122e11121113111112131130102e1112132e12100f0002b70001148d1212132f121112131230122e11141013122f122e141012131230121112301212121211301113122e132e13111215122f112e132e122f12131211132e1312122e100002b50001158d11301113122e122f11131113112e122f12121212122e122e1212122f1311112f132e1211132d12121213112e132e1311121213111114102f122e1311132d121211000d05",
                            "off": "2600d8000001168c122e1213102f112e13121013112e123010131112122e112f1113122d1213112e122f122d1212112e1312101311121113121112121112122d12141012112f12110e0002b60001168c1213113012121212112f132f11141113112f123012121113112f1213113112131014101510301113112f142d132e132e132d132f122e12131130122f1312122d0e0002b60001168c122f1113112f122f121210150f2f122e12141014102f122e1213112e1213112f122e122e1312112e1214101311131114101211141212112f12121113122e13110f000d05",
                            "temperatureCodes": {
                                "17": {
                                    "rotationSpeed99": "2600d8000001158d122e1211122e122e14101211132d122f11131012122f112e1213122f1013122d132d12111212122f1111131310131112121112121112112f11141012132d1111110002b40001178b1312132e13111113122e132e12131412132e132d12121312142e1212132e11141113112f132f1113122e112f132f122e132e122e132e1313132d132f1211142d0f0002b60001148d112f1212122e122f12131212112f122f121211131130112e1212142d1211132e122e12121212132d1212131112131211121211121213112e141012121230101110000d05",
                                    "rotationSpeed66": "",
                                    "rotationSpeed33": ""
                                },
                                "18": {
                                    "rotationSpeed99": "2600d8000001168c122f1014102e122e12131112122d142c12131211112f122f1013122e1312122e102e12131211122d132d121310141112111211131112132d11121312102f13100e0002b60001158d1410132f11121312132e122f12131113122e123012141112122e1213122e12131113122f122e12121311142e122f122f112f122e132e1213122f122f1312112f0d0002b60001178c112f12121130102f12131015102e122f12111213112f122e111311301013122e122e12131212112f132d121311121211121213111213113013111214102f11110f000d05",
                                    "rotationSpeed66": "200688..."
                                },
                                "19": {
                                    "rotationSpeed99": "2600d8000001158d122e12111230112e11121112122f112f11121211122f112e1213112e1113122d132d12121212122e11111311122e1114101312111311132d13101212122e13100f0002b60001158c1213132e11131212122f142d111412111230122e12121215112f1212132e111412111230112e13121230112e1214122d142e122f122f12131130112e1411132d0e0002b70001148d132d1213112e122f12121112122f122f121113121130112e1412122d1312112f122e12131112122f12121311132e1112141012131112122e14111113112e12120e000d05",
                                    "rotationSpeed66": "200688..."
                                },
                                "20": {
                                    "rotationSpeed99": "2600d8000001158c122f1114102e122e12141111122e112e12131112122d122e1312122d1311122d122e13131012112e132d122f121210141112111312130f2e12131013122d12120e0002b60001158e1213113011141013112f132f10150f14122f112e121410150f2f1214112e12131213142c142d131212121114122e122e132e122f122e1313112e132f1114112e0f0002b60001158c132f1114112e132d13121113102f132f10131213102f112f1213102f1213122e113012121212102f1130112e12131114101410131114112d13121114102f11120e000d05",
                                    "rotationSpeed66": "200688..."
                                },
                                "21": {
                                    "rotationSpeed99": "2600d8000001168c122f1211112e142d11131111132d132d13111213102e122e1212142d1211132f102e13111211132f1012122e122e1311131111131012122e12121112122f11110f0002b80001158c1113132e12121311132e142d12121212142e122f11121311122f1311132f11131112132e132e1212123012131112142e122e122e122f1212132e132f1212132c100002b60001158c122f1113112f122e13111311122e132d14101312112f122e1113132d1213112e132d12131112122f1212112f122e1213111212121113122f12111212122e140f0f000d05",
                                    "rotationSpeed66": "200688..."
                                },
                                "22": {
                                    "rotationSpeed99": "2600d8000001168c122e1113132e122f11121113122e112f11131013112f122e1311112e1213112e122f12121013112e122f1211112e1213111311121112112e12121113112e12120f0002b50001158d1213113011141113122e122f11141113112f122f13121015112e1214122e12131212132e113011131113132d1213122f122e122f142e1015112d132e1412112d100002b60001158c112f1312122e112f11151013112f122f11131213112e122e1113122e1213112f122e111311131130112e1213112e1213111310141114103010151012113011120e000d05",
                                    "rotationSpeed66": "200688..."
                                },
                                "23": {
                                    "rotationSpeed99": "2600d8000001168c122f1211112e142d11131111132d132d13111213102e122e1212142d1211132f102e13111211132f1012122e122e1311131111131012122e12121112122f11110f0002b80001158c1113132e12121311132e142d12121212142e122f11121311122f1311132f11131112132e132e1212123012131112142e122e122e122f1212132e132f1212132c100002b60001158c122f1113112f122e13111311122e132d14101312112f122e1113132d1213112e132d12131112122f1212112f122e1213111212121113122f12111212122e140f0f000d05",
                                    "rotationSpeed66": "200688..."
                                },
                                "24": {
                                    "rotationSpeed99": "2600d8000001168c122e1014112f112f0f1410140f310f31121110140f31112f0f14103010140f31122e0f141014122e10301030122e10140f310f1410140f3210300f14103010130d0002b80001138f1213103011140f161130103110141014113010311014101510301015103011141014103110310f150f150f15101510301014113011301014101510311113112f0e0002b80001158d0f31121210310f31111311130f310f3110140f150f31103111130f310f150f3110311112101410310f3110310f3111130f31101410140f3110310f150f310f140d000d05",
                                    "rotationSpeed66": "2600d8000001148e132d111310301030101311131030103010131113103010301013112f11131030103010131114112f11301030103010131113101311130f31122e1014103010120d0002b90001148e1312103010150f15103110301114101411300f320f150f1510310f1511300f150f1510310f320f150f150f15101510301130103110310f15101410310f150f300d0002b90001138f0f310f150f3110310f150f1410310f31101410140f3110310f150f3110140f3110301113101410310f310f31132f101410140f150f150f320f31101410310f130d000d05",
                                    "rotationSpeed33": "2600d8000001148e112f111310300f31101311131030103010131113102f112f111310311112112f112f11131013112f112f112f112f111310301030112f1113102f1113112f11120c0002b90001138f1113113011131015103010310f1510141130103112150f151030111411300f1510141031112f1114141110141015112f11140f151014132e1015122e1015102f0d0002b80001138f0f31101410310f310f150f150f310f3110140f150f3110310f150f310f150f3110310f150f1410310f31103010310f150f31132f0f3110140f31101410310f130e000d05"
                                },
                                "25": {
                                    "rotationSpeed99": "2600d8000001138f103010131030122e111310140f30112f11131013103011301013112f11151030103010131113102f111311131013112f103011131013112f112f1015103010120d0002b800011390121310310f150f1510310f3210140f15103110310f150f1510310f1510310f150f161031113010140f3210310f3110141115103110310f150f1510321015112e0d0002b80001138f10310f150f3110301014101410310f310f150f150f31103010150f310f150f3110310f150f1410310f14101410140f320f310f150f1512300f31101410310f130d000d05",
                                    "rotationSpeed66": "2600d8000001158c10301212122e122e11121212132e122e12121014122e122e12120f3012121030122e12111113112f121112121114112f111212121013112f122e1014112e12110d0002b80001158d12131130101411141031103010141015103011300f15101510301015103010141114113010310f151031103110301015122f1031103010150f151030111410300d0002b80001138f112f1212122f10310f15111210310f3110141113103010310f150f31121210310f3111130f150f311113111311131031111212121212103111301113112f11120d000d05",
                                    "rotationSpeed33": "2600d8000001138f0f311013112f112f11131112112f103011131013112f112f1212112f11141130112f111210140f31111211131013112f112f112f10301212112f1112112f11120d0002b80001168c11141130101411141030113010150f151031103010141015132f0f1510310f151014103110311014103110301130101410141015101410310f1510310f15102f0d0002b80001168d112f11130f3110310f150f150f310f31121211130f3110310f150f3111130f31103112130f150f311212121211130f3110310f3110310f15112f1113103111120d000d05"
                                }
                            }
                        },
                        "auto": {
                            "on": "2600d8000001158c112f1114112d132e11131111142c122f11121212112e122f1113122e1212112f112e1312112e12111212132e122e11121113111112131130102e1112132e12100f0002b70001148d1212132f121112131230122e11141013122f122e141012131230121112301212121211301113122e132e13111215122f112e132e122f12131211132e1312122e100002b50001158d11301113122e122f11131113112e122f12121212122e122e1212122f1311112f132e1211132d12121213112e132e1311121213111114102f122e1311132d121211000d05",
                            "off": "2600d8000001168c122e1213102f112e13121013112e123010131112122e112f1113122d1213112e122f122d1212112e1312101311121113121112121112122d12141012112f12110e0002b60001168c1213113012121212112f132f11141113112f123012121113112f1213113112131014101510301113112f142d132e132e132d132f122e12131130122f1312122d0e0002b60001168c122f1113112f122f121210150f2f122e12141014102f122e1213112e1213112f122e122e1312112e1214101311131114101211141212112f12121113122e13110f000d05",
                            "temperatureCodes": {
                                "17": {
                                    "rotationSpeed100": "",
                                    "rotationSpeed66": "",
                                    "rotationSpeed33": ""
                                },
                                "18": {
                                    "rotationSpeed100": "2600d8000001168c122f1014102e122e12131112122d142c12131211112f122f1013122e1312122e102e12131211122d132d121310141112111211131112132d11121312102f13100e0002b60001158d1410132f11121312132e122f12131113122e123012141112122e1213122e12131113122f122e12121311142e122f122f112f122e132e1213122f122f1312112f0d0002b60001178c112f12121130102f12131015102e122f12111213112f122e111311301013122e122e12131212112f132d121311121211121213111213113013111214102f11110f000d05",
                                    "rotationSpeed66": "200688..."
                                },
                                "19": {
                                    "rotationSpeed100": "2600d8000001158d122e12111230112e11121112122f112f11121211122f112e1213112e1113122d132d12121212122e11111311122e1114101312111311132d13101212122e13100f0002b60001158c1213132e11131212122f142d111412111230122e12121215112f1212132e111412111230112e13121230112e1214122d142e122f122f12131130112e1411132d0e0002b70001148d132d1213112e122f12121112122f122f121113121130112e1412122d1312112f122e12131112122f12121311132e1112141012131112122e14111113112e12120e000d05",
                                    "rotationSpeed66": "200688..."
                                },
                                "20": {
                                    "rotationSpeed100": "2600d8000001158c122f1114102e122e12141111122e112e12131112122d122e1312122d1311122d122e13131012112e132d122f121210141112111312130f2e12131013122d12120e0002b60001158e1213113011141013112f132f10150f14122f112e121410150f2f1214112e12131213142c142d131212121114122e122e132e122f122e1313112e132f1114112e0f0002b60001158c132f1114112e132d13121113102f132f10131213102f112f1213102f1213122e113012121212102f1130112e12131114101410131114112d13121114102f11120e000d05",
                                    "rotationSpeed66": "200688..."
                                },
                                "21": {
                                    "rotationSpeed100": "2600d8000001168c122f1211112e142d11131111132d132d13111213102e122e1212142d1211132f102e13111211132f1012122e122e1311131111131012122e12121112122f11110f0002b80001158c1113132e12121311132e142d12121212142e122f11121311122f1311132f11131112132e132e1212123012131112142e122e122e122f1212132e132f1212132c100002b60001158c122f1113112f122e13111311122e132d14101312112f122e1113132d1213112e132d12131112122f1212112f122e1213111212121113122f12111212122e140f0f000d05",
                                    "rotationSpeed66": "200688..."
                                },
                                "22": {
                                    "rotationSpeed100": "2600d8000001168c122e1113132e122f11121113122e112f11131013112f122e1311112e1213112e122f12121013112e122f1211112e1213111311121112112e12121113112e12120f0002b50001158d1213113011141113122e122f11141113112f122f13121015112e1214122e12131212132e113011131113132d1213122f122e122f142e1015112d132e1412112d100002b60001158c112f1312122e112f11151013112f122f11131213112e122e1113122e1213112f122e111311131130112e1213112e1213111310141114103010151012113011120e000d05",
                                    "rotationSpeed66": "200688..."
                                },
                                "23": {
                                    "rotationSpeed100": "2600d8000001168c122f1211112e142d11131111132d132d13111213102e122e1212142d1211132f102e13111211132f1012122e122e1311131111131012122e12121112122f11110f0002b80001158c1113132e12121311132e142d12121212142e122f11121311122f1311132f11131112132e132e1212123012131112142e122e122e122f1212132e132f1212132c100002b60001158c122f1113112f122e13111311122e132d14101312112f122e1113132d1213112e132d12131112122f1212112f122e1213111212121113122f12111212122e140f0f000d05",
                                    "rotationSpeed66": "200688..."
                                }
                            }
                        }
                    }
                }
            ]
        }
```

**Comment by kiwi-cam** [comment]
The latest beta should resolve this.

**Comment by hamwong** [comment]
with unknown reason, it suddenly no longer pop error, i didn't install beta yet

**Comment by hamwong** [comment]
I got a off topic question, is there a way that use mqtt post/update changes on status? for example once change(issue IR) temp to 23, post/revice status on mqtt custom topic?
cause I found it's difficult to syn status with home auto system

**Comment by kiwi-cam** [comment]
Listening for IR codes is something that has come up a few times. It's technically possible but I believe you'd need a dedicated device in "listen"/learn mode full time... then it would be possible to react to IR codes.

I've just never had the time to investigate it fully.

**Comment by hamwong** [comment]
@kiwi-cam 
sorry for my bad English, what I mean is once plugin issue IR, can It also post an update on MQTT custom topic?
for example, if it just issue temp 20, it will post tele/LivingR/AirCon/temp20, so home auto system aware the changes, also plug can subscribe a mqtt topic (like temperature). if I issue command on home auto system, plugin will also aware changes and update on homebridge (homekit), eg I change the temp to 25 again on home auto system, so plugin will update target temp as 25
