### ISSUE TITLE
Unable to restart homebridge after update

### ISSUE THREAD

**Issue by onixx** [kiwi-cam/homebridge-broadlink-rm#430]
**Describe the bug**
I just upgraded from 4.4.6 to 4.4.8 and homebrige won't restart.

I see this in the log
[12/23/2021, 4:32:11 PM] RangeError: Maximum call stack size exceeded
    at Function.Array.from (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/homebridge/node_modules/homebridge-broadlink-rm-pro/node_modules/collections/shim-array.js:31:22)

Hobebridge is in a restart loop, If i uninstall the plugin, everything returns to normal

**Comment by onixx** [comment]
I think something is happening with an updated dependency

**Comment by onixx** [comment]
Update: uninstalling and reinstalling did not work. Reinstalling 4.4.6 did not work either. 

 i had an overnight backup of node_module dir before the update for homebridge. Restored the broadlink-rm-pro directory and i am back up. 
 
There is a dependency that is breaking something

**Comment by 1rado1** [comment]
Same issue here, wondering how to fix it. So far no success. Happened today since I was forced to reinstall / new image of fresh homebridge on SD

**Comment by modul8co** [comment]
I was able to fix this by navigating to terminal, and running:

sudo npm update -g

I also fixed the vulnerabilities found, including force.

I cleared the npm cache before running these.

After reinstalling the plugin, everything works.

**Comment by onixx** [comment]
Fixed with latest release
