### ISSUE TITLE
Pronto IR Codes Issue

### ISSUE THREAD

**Issue by jeylites** [kiwi-cam/homebridge-broadlink-rm#46]
All was working great until yesterday, my broadlink IR devices stoped working and it seem that the plugin isn't able to read Pronto IR, I'm getting the following error. It seem to work OK on normal hex codes. 

```
[8/31/2020, 19:07:26] [Broadlink RM] Air Conditioner Advanced getCurrentHeatingCoolingState: 2
[8/31/2020, 19:07:26] [Broadlink RM] Air Conditioner Advanced getTargetTemperature: 18
[8/31/2020, 19:07:26] [Broadlink RM] Air Conditioner Advanced getTargetHeatingCoolingState: 2
[8/31/2020, 19:07:26] [Broadlink RM] Air Conditioner Advanced getCurrentTemperature (using pseudoDeviceTemperature 26 from config)
[8/31/2020, 19:07:26] [Broadlink RM] TV On/Off getSwitchState: false
[8/31/2020, 19:07:27] [Broadlink RM] 
[8/31/2020, 19:07:27] [Broadlink RM] **************************************************************************************************************
[8/31/2020, 19:07:27] [Broadlink RM] ** Welcome to version 4.0.5 of the Homebridge Broadlink RM Plugin!
[8/31/2020, 19:07:27] [Broadlink RM] ** 
[8/31/2020, 19:07:27] [Broadlink RM] ** Find out what's in the latest release here: https://github.com/lprhodes/homebridge-broadlink-rm/releases
[8/31/2020, 19:07:27] [Broadlink RM] ** 
[8/31/2020, 19:07:27] [Broadlink RM] ** If you like this plugin then please star it on GitHub or better yet
[8/31/2020, 19:07:27] [Broadlink RM] ** buy me a drink using Paypal https://paypal.me/lprhodes or crypto https://goo.gl/bEn1RW.
[8/31/2020, 19:07:27] [Broadlink RM] ** 
[8/31/2020, 19:07:27] [Broadlink RM] ** Keep up to date with this plugin along with everything HomeKit and homebridge
[8/31/2020, 19:07:27] [Broadlink RM] ** by signing up to my newsletter at http://workswith.io
[8/31/2020, 19:07:27] [Broadlink RM] **
[8/31/2020, 19:07:27] [Broadlink RM] ** You can disable this message by adding "hideWelcomeMessage": true to the config (see config-sample.json).
[8/31/2020, 19:07:27] [Broadlink RM] **
[8/31/2020, 19:07:27] [Broadlink RM] **************************************************************************************************************
[8/31/2020, 19:07:27] [Broadlink RM] 
[8/31/2020, 19:21:20] [Broadlink RM] TV On/Off setSwitchState: true
(node:6563) UnhandledPromiseRejectionWarning: TypeError: log is not a function
    at prontoToLIRC (/usr/local/lib/node_modules/homebridge-broadlink-rm-tv/helpers/convertProntoCode.js:16:12)
    at convertProntoToBroadlink (/usr/local/lib/node_modules/homebridge-broadlink-rm-tv/helpers/convertProntoCode.js:68:22)
    at sendData (/usr/local/lib/node_modules/homebridge-broadlink-rm-tv/helpers/sendData.js:16:15)
    at SwitchAccessory.performSend (/usr/local/lib/node_modules/homebridge-broadlink-rm-tv/accessories/accessory.js:45:7)
    at SwitchAccessory.setSwitchState (/usr/local/lib/node_modules/homebridge-broadlink-rm-tv/accessories/switch.js:105:29)
    at SwitchAccessory.setCharacteristicValue (/usr/local/lib/node_modules/homebridge-broadlink-rm-tv/node_modules/homebridge-platform-helper/accessory.js:139:10)
    at On.emit (events.js:315:20)
    at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:60:38)
    at On.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:369:23)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:951:36
    at Array.forEach (<anonymous>:null:null)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:819:18)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:60:38)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:731:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:240:39)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

(node:6563) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6563) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[8/31/2020, 19:21:24] [Broadlink RM] TV On/Off setSwitchState: false
(node:6563) UnhandledPromiseRejectionWarning: TypeError: log is not a function
    at prontoToLIRC (/usr/local/lib/node_modules/homebridge-broadlink-rm-tv/helpers/convertProntoCode.js:16:12)
    at convertProntoToBroadlink (/usr/local/lib/node_modules/homebridge-broadlink-rm-tv/helpers/convertProntoCode.js:68:22)
    at sendData (/usr/local/lib/node_modules/homebridge-broadlink-rm-tv/helpers/sendData.js:16:15)
    at SwitchAccessory.performSend (/usr/local/lib/node_modules/homebridge-broadlink-rm-tv/accessories/accessory.js:45:7)
    at SwitchAccessory.setSwitchState (/usr/local/lib/node_modules/homebridge-broadlink-rm-tv/accessories/switch.js:105:29)
    at SwitchAccessory.setCharacteristicValue (/usr/local/lib/node_modules/homebridge-broadlink-rm-tv/node_modules/homebridge-platform-helper/accessory.js:139:10)
    at On.emit (events.js:315:20)
    at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:60:38)
    at On.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:369:23)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:951:36
    at Array.forEach (<anonymous>:null:null)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:819:18)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:60:38)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:731:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:240:39)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

(node:6563) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

Config

```
 {
                    "name": "TV On/Off",
                    "type": "switch",
                    "data": {
                        "on": "0000 006D 0000 0043 00B3 0064 000F 000F 000F 0025 000F 0025 000F 000F 000F 0025 000F 000F 000F 000F 000F 000F 000F 000F 000F 0025 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 0025 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 0025 000F 0025 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 0025 000F 0025 000F 0025 000F 000F 000F 0025 000F 000F 000F 000F 000F 000F 000F 0025 000F 000F 000F 000F 000F 000F 000F 0025 000F 0025 000F 000F 000F 000F 000F 0300 00B3 0219",
                        "off": "0000 006D 0000 0043 00B3 0064 000F 000F 000F 0025 000F 0025 000F 000F 000F 0025 000F 000F 000F 000F 000F 000F 000F 000F 000F 0025 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 0025 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 0025 000F 0025 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 000F 0025 000F 0025 000F 0025 000F 000F 000F 0025 000F 000F 000F 000F 000F 000F 000F 0025 000F 000F 000F 000F 000F 000F 000F 0025 000F 0025 000F 000F 000F 000F 000F 0300 00B3 0219"
```
                    }

**Comment by jeylites** [comment]
Plugin issue, switch to  the following and it worked.


https://www.npmjs.com/package/homebridge-broadlink-rm-tv

**Comment by jeylites** [comment]
Latest update fix the issue.. 4.2.9 of the Homebridge Broadlink RM Plugin
