### ISSUE TITLE
heater-cooler error (Missing HEX)

### ISSUE THREAD

**Issue by mauriciofarina** [kiwi-cam/homebridge-broadlink-rm#537]
I'm trying to run a simple heater-cooler accessory. It works just fine for some commands until it gives me the error on the logs below: 

```
[9/24/2022, 9:38:13 PM] [Broadlink_Living] [DEBUG] Ar Condicionado Sala addTemperatureCallbackToQueue (requested temperature from device, waiting)
[9/24/2022, 9:38:13 PM] [Broadlink_Living] Ar Condicionado Sala getActive: 0
[9/24/2022, 9:38:13 PM] [Broadlink_Living] Ar Condicionado Sala getCoolingThresholdTemperature: 25
[9/24/2022, 9:38:13 PM] [Broadlink_Living] Ar Condicionado Sala getCurrentHeaterCoolerState: 0
[9/24/2022, 9:38:13 PM] [Broadlink_Living] Ar Condicionado Sala getTargetHeaterCoolerState: 2
[9/24/2022, 9:38:13 PM] [Broadlink_Living] Ar Condicionado Sala getHeatingThresholdTemperature: 26
[9/24/2022, 9:38:13 PM] [Broadlink_Living] Ar Condicionado Sala setCurrentHeaterCoolerState: 0
[9/24/2022, 9:38:13 PM] [Broadlink_Living] Ar Condicionado Sala setCurrentHeaterCoolerState: already 0 (no data sent - B)
[9/24/2022, 9:38:13 PM] [Broadlink_Living] [DEBUG] Ar Condicionado Sala onTemperature (0)
[9/24/2022, 9:38:18 PM] [Broadlink_Living] Ar Condicionado Sala setActive: 1
[9/24/2022, 9:38:18 PM] [Broadlink_Living] Looking up temperature hex codes for 25
[9/24/2022, 9:38:18 PM] [Broadlink_Living]      Sending hex codes for temperature 25
[9/24/2022, 9:38:18 PM] [Broadlink_Living]      Adding ON code first
[9/24/2022, 9:38:18 PM] [Broadlink_Living] Ar Condicionado Sala setTargetHeaterCoolerState: 2
[9/24/2022, 9:38:18 PM] [Broadlink_Living] Ar Condicionado Sala setTargetHeaterCoolerState: already 2 (no data sent - B)
[9/24/2022, 9:38:18 PM] AssertionError [ERR_ASSERTION]: [ERROR]: Ar Condicionado Sala sendData (HEX value is missing)
    at module.exports (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/helpers/sendData.js:7:3)
    at HeaterCoolerAccessory.performRepeatSend (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:116:7)
    at /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:97:20
    at catchDelayCancelError (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/helpers/catchDelayCancelError.js:8:20)
    at HeaterCoolerAccessory.performSend (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:92:11)
    at HeaterCoolerAccessory.setActive (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/heater-cooler.js:430:16)
    at HeaterCoolerAccessory.setCharacteristicValue (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:145:9)
    at Active.emit (node:events:527:28)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1725:16
    at new Promise (<anonymous>)
```

My accessory configuration:

```json
 {
                    "name": "Ar Condicionado Sala",
                    "type": "heater-cooler",
                    "minTemperature": 16,
                    "maxTemperature": 30,
                    "tempStepSize": 1,
                    "noHumidity": true,
                    "noHistory": true,
                    "data": {
                        "heat": {
                            "off": "260068011100024b600001280e130e330e130e120f120e130e120f120e120f330e120f120e340d340e130d340e3310310f330e330e130e120e130e120f120e130e130e130d130e130d140e120e130e120f120e130e120f120e120f120e130e120f120e130e130f120d130e130d130e1310110e120f120e120f330e330e64600001280e330e140d130e130d130e130d140e120e130e330e130e120f330e120e330f330e340d340d340d340f120e130e120e130e120f120e130e120f120e120f120e130e130e130d130e130d140d130e1310100f120e130e120f120e120f120e1310100f120e130e130e130d130e130d130e130e64600001280e330f120e120f120e130e120f120e130e120e340e130d130e340d340e330e330f120e3310310f33103110320f320e330e340e120e130e120f330e330e330e130e120f120e130e130e130d130e130d130e340e330e130e330e330e130e120f120e130e120e140d130e130d130e340e330e000d05",
                            "on": "",
                            "temperatureCodes": {
                                "16": "2600f2001300024c6300012510111031110f1110111010101110101011101130120f1110113010110f120f3210311130113110311011101011101010111010120f11101110100e130f120f11101110101110101110101110101011101110101011101011101110110f110f120f1110111011101011301131113011301162620001251131111010100f12101110101110110f120f1130120f110f1230110f12301131101011300f33103111301130122f123011301110110f1210103110310f3211101011110f120f110f120f1110110f120f1130122f1210103111100f110f3211101110110f120f111011301130113012300f000d05000000000000",
                                "17": "2600f2001400024b620001251210103110111010111010111010111010101130120f1110103111101010113111301131103110311110101011101110101011101110101011101011101110101011101110101110101110101110101011101110101011101010111011101011101010110f12101110311031113011301261620001251230110f11101011101110110f1110111010113110101110101011101130122f120f113012310f3210311031103111301230110f111011101031103111301111101010111011101010311110111010101130113110101131110f1110103210110e12101110101110103111301230113011000d05000000000000",
                                "18": "2600f2001400024b62000125120f11311110101011101011110f1110110f1230110f120f11311010110f12301130113110311031120f1110110f1110110f120f1110110f120f1110110f111011101110101011101011110f1110110f120f1110110f120f110f120f1110110f120f111011101011103110311130122f1260640001241231100f120f1110110f1110111011101010113110101110110f120f1130122f120f122f1230113011301131113010321130110f120f1110113011301131110f1110110f12101010111010311110110f122f1230110f1230110f120f112e13101110111010101110103111301230113011000d05000000000000",
                                "19": "2600f2001400024b62000125120f1131111010101110101110101110110f1230110f120f1130120f110f1131113110311031103111101110110f120f110f1110120f110f120f11101010111011101011101011101011101011101110110f120f1010120f1110110f1110110f11101110111010110f321031113012301161620001261130110f1110111010101110111010110d141031101011101031122f120f122f120f1130122f123011310f32103110311130120f120f110f123011301130120f101110111010111010311130120f120f11301130120f113011101010113110111011101010111010113012301130122f12000d05000000000000",
                                "20": "2600f2001400024b62000125120f10311110101011111010111010111010112f130f11101130110f120f1130122f123110310d341011101011101010120f120f110f11101110110f1110110f11101110110f1111101011101010111011101010120f111010101110110f11101110110f111011101032103110311031126063000125122f120f11101010120f111010101110110f113111100f12101011101031122f120f1130122f123011301130123011301131101011101010113111301130120f110f11101110110f12100f110e33111010311130120f1130120f11101031110f120f120f110f1210103110311130113111000d05000000000000",
                                "21": "2600f2001400024b62000125120f1130120f1110110f11101110101110101131101011101031120f110f113111301130122f122f121010111010101110101110111010101110110f120f1110110f1110111010101110110f1111101011101011101011101011110f11101010111011101010120f1130122f12301131116063000125113110101110111010101110110f1110111011301110101012300e331110103111101130122f122f12301130113012301130111010111010113012301130120f110f120f110f11101131110f1131111010311031111010311110110f1130120f1110110f11101110113011311031103112000d05000000000000",
                                "22": "2600f2001400024c5f000129110f10320d131110101110101110110f120f122f120f11101130110f120f113012301130113110311110110f1110110f120f120f110f120f111010101110111010110d1311101011101011101010120f120f110f111011101010120f110f120f1110101110111010113011311031122f126162000125122f120f1110101011101110101111100d1310311110101110311130120f1130111011301130113011311031113110311130120f110f120f1130122f1230110f121010100e131011101011301131110f122f1230110f1130120f120f1131101011101011101011101031122f1230113011000d05000000000000",
                                "23": "2600f2001400024a630001251110103111101110110f1110110f120f1110113011101010113011111010113110311031122f122f120f120f110f111011101010120f111010110d141010101110101110111010101110110f1110111010101110111010101110101110110d1311101011101011101130122f1230113011616200012611301110101110110f11101110101110111010311110101011101031120f1031111010311131103110311130123011301130120f101011101130123010311110101110101110111011301130122f120f1130122f120f11310d141010103111101110101011101110103111301130122f12000d05000000000000",
                                "24": "2600f2001400024c62000125120f1130120f101011101110101011110f111031111010111031110f120f1130122f12301130113011111010101110101110101110101110111010101110110f11101110101011101110101011110f11101110101110101110101110110f1110111010101110111010311130123011301260630001251031111011101010111011101010111010101131110f1110111010110d34103111101130122f123011301130122f12301131101010111010113110311130120f1010120f1110110f11101110101011311130112f12101130120f111011301110110f111010101110113011311130113111000d05000000000000",
                                "25": "2600f2001200024d6200012511101130111010101110111010111011101010320f111011103111101010113011311031113011311011101010110f120f11111011101010111010101110111010101110101011101110101110110d1310110f120f1110111010111011101010111010111010111010311130113110311161630001251131101011101010111011101010111011101031101110111031103110110f32111010311130113011311031103111310e3310110f120f1111301131103111101010111010101110113011110f11113010320f32111010311010111011301110111010101110101110310e340f320f3211000d05000000000000",
                                "26": "2600f2001400024b6200012512100d3410101110111010101110111010101130120f111010311110101011311130113110311031120f110f1110111010101110110f11101110101011110f110e1310101110101110101110111010101110110f1110120f1010120f1110110f11110f1110111010113110311130122f126162000125122f120f11101010120f111011101011101011301110111011301130120f113011101031113012300d34113110311130122f120f110f120f1130123011301110101110101110101110101130120f122f12301130110f1131110f11101131101110101011101011101130122f1230113011000d05000000000000",
                                "27": "2600f2001400024b6300012511101031120f110f120f120f1010120f11101031110f120f1131111010101130113111301130122f120f1110101011101110110f12100f110e1310101110101110101110110f11101110110f11101110110f11101010120f111011100d141010111010111010111011301130122f12300e64620001271030111011101011101010111010111011101031110f120f11101130110f1131110f11310e3311311031122f122f123011301110101011101130113110311110101110101110110f12301130110f1230113011301210103110101110103111101110110f120f110f123011301130122f11000d05000000000000",
                                "28": "2600f2001400024b630001251110113011100e13101011101011101011101130120f110f122f120f111010311130123010311131101011101110110f1110110f1110120f1010120f11101010120f1110101110101110101110101110110f11101110110f120f1110110f11101010120f1110101110311031113111301161620001261130120f110f111011101010120f101110110d341011101011301230110f1230110f122f12301130113111301031113110311110110f120f11301130122f120f120f110f12100d131110101110311031122f122f120f1130120f11101130111011100d131110101110311031122f123011000d05000000000000",
                                "29": "2600f2001400024b62000126110f1230110f1110110f11101110111011101031101110101130120f120f11301130122f1230113011101110101011101011101011101110110f1110110f111011101010120f110f1110111011101011101011101011101011101010120f120f1010111011101010113012301131103111606300012610311110110f120f110f1110120f110f11101130120f10111011103110111031101110311130122f122f12301130113012301110101011101031122f1230110f120f1110110f11101031120f113110311031103111101130120f110f1230110f1110111010101110113110311031113012000d05000000000000",
                                "30": "2600f2001500024b61000126120f113011100e1310111010101110101110122f120f110f1131110f11101131112f12301131103110101110120f110f120f11101010120f110f111011101010111011101011101110101011101011101110110f1110110f120f1110110f111011101010120f10111031113110311031126162000125122f120f111010101110110f120f111010110d341110101110101130120f1130120f1130122f122f12301131103110311130120f11101010113111301130120f10101110111010110d14103110311130122f1230110f122f120f111011301110111010111010111010311130122f123011000d05000000000000"
                            }
                        },
                        "cool": {
                            "off": "260068011100024b600001280e130e330e130e120f120e130e120f120e120f330e120f120e340d340e130d340e3310310f330e330e130e120e130e120f120e130e130e130d130e130d140e120e130e120f120e130e120f120e120f120e130e120f120e130e130f120d130e130d130e1310110e120f120e120f330e330e64600001280e330e140d130e130d130e130d140e120e130e330e130e120f330e120e330f330e340d340d340d340f120e130e120e130e120f120e130e120f120e120f120e130e130e130d130e130d140d130e1310100f120e130e120f120e120f120e1310100f120e130e130e130d130e130d130e130e64600001280e330f120e120f120e130e120f120e130e120e340e130d130e340d340e330e330f120e3310310f33103110320f320e330e340e120e130e120f330e330e330e130e120f120e130e130e130d130e130d130e340e330e130e330e330e130e120f120e130e120e140d130e130d130e340e330e000d05",
                            "on": "",
                            "temperatureCodes": {
                                "16": "2600f2001400024c62000125120f113011101010111010111011101110101031111011101031110f11101130122f123011301131101110101110101110101110101011101110101011101110101011101010111011101011101110101110101110101110110f120f111010101110110f111011101031113110311031126063000125122e121011101110101011101010111011101031111010111031101110311130120f1130122f122f12301130113111301131101011101010113111301130120f1010111011101010111010110e13101110311031111010311130120f101011101110101011101011103111311031103112000d05000000000000",
                                "17": "2600f2001400024b6300012511101130120f111010101110110f11101110103111101011103110111010113111301130122f122f120f1110101011101110111010110f111110101110101110110f1110111010101110111010101110110f111011101110111010101110101110101110110f11101130122f1230113011616300012610310d14101010111010111011101010120f1130120f110f111011101130113011110f3210311031122f123011301130122f120f1110110f11310e331131101011101110101011101130120f110f11101130122f1210103110311110101110101110110f120f120f10311130122f123011000d05000000000000",
                                "18": "2600f2001400024c6200012512100f3210101110101110101110110f120f122f120f11101031110f111011311130113011311031120f110f111011101010120f110f11101110110f11111010101110111010101110101110120f1010120f110f11101110110f11101110101011110f110e131011103110311130122f1261620001251230110f11101110110f111110100e131010113110101110110f120f1130122f120f122f12301131103110311031113111301110110f1110113011301130120f11110f110f12101011101031120f110f113111301110103111301110101011110d13111010101110113012301031113012000d05000000000000",
                                "19": "2600f2001300024c63000125101110311110110f120f110f120f1110110f122f120f111011311010120f10311130123011301130120f110f120f1110110f120f111011101011101010111010120f1110110f120f1110110f120f110f120f1110110f120f111011101011110f10111010120f111011301130113012301161630001251131101011101010111010111010120f11101130110f120f1130122f120f11311110103111301031123011301130122f1230110f120f111011311031103110111010120f110f120f1130122f120f120f1130113012101031103110111010120f1110110f120f110f123011301130122f12000d05000000000000",
                                "20": "2600f2001400024b6200012611101031110f120f11101010111110100e131031101110101131110f11101130122f122f123011311010101110111010111010111010111010101110111010101110110f111011101010121010100e13101110101110101011101110110f1110111010101110101011311130113111301260630001251130120f111010101110110f1110111010101130120f1110101110111031103111101031122f122f12301130122f123011310f1110111010113111301130120f110f11101110101011101110103111100e331131101011301230110f11101110110f111010101110113011310f32113111000d05000000000000",
                                "21": "2600f2001400024b6300012610101130120f11101010120f1110101011101130120f101110311110101110311130122f122f1230110f1110111010101110111010110f121010101110101110111010101110110f11101110110f120f111010101110111010111011101010111010111011101010113012301130113011626200012611300e1310101110101110101110110f11101130120f1110103111301110103210100f32113110311130122f123011301130120f110f111110311031113011101110110f1110120f1130110f1131110f1131113110100f32113110101110111010101110110f120f1130122f1230113110000d05000000000000",
                                "22": "2600f2001400024b6300012511101130120f1110110f1110110f11101110103111101010123011101010113110311130122f122f120f120f110f11101110101011110f110e13101110101110101011101110110f1110110f11101110110f11101110101011110f1110111010111010111010120f1130122f12301130116162000126113012100f111011101011101011101011101130120f110f122f1230110f113111101031113110311031122f122f123011301110101011101131103110311110101110101110110f11101130122f120f1130123011101031103111101011101011101110110f11101130122f122f123011000d05000000000000",
                                "23": "2600f2001400024c62000125120f1130120f110f111011101010121010100e3410101110103111101010113012301130122f122f120f11110f11101110101110101110101110110f120f1110110f11101110101011101010120f111010110f1210101110101110101110110f120f1110110f120f1130122f123011301161630001251131101011101110110f11101110101011101031120f1010111011310d1410311010113111301130122f122f12301130113111100d131110103111301230110f1110110f1110111010311130123010110d34103111101031122f120f111010101110110f11101110113011310d34103112000d05000000000000",
                                "24": "2600f2001100024f6100012611101031101110101110101110110e1210110f3210110f12103110101110113011301131103110320e13101010110f1110110f121010111011101010111010101110111010101110101110110e130f110f120d1310110f1210101110101110101110101011101011103110320f3210311161630001251130111011101010111011101010111010111031101110110f1111100f321030121011301131103110311130113110320f320f1110110f1210311031113011101110101011101010111011101011103111310f320f111131103110111010111010101110111010101131103110320f3211000d05000000000000",
                                "25": "2600f2001300024d6100012611101031101110101110101110110f120f110e330e130f121031101011101130113110311031103111110f1110110f120d130e130f111110101110101110101110101011101011101011101110110f11101110110d130f121010111010111010111010101110101110311031113110311161620001260f3310101110101011101110101011101011103110101110103210310f120d3410111031103111301131103110311131103110110d140d130f321131103111101010111010111010113011110f120f320f320f32101110311031120f101011101110101011101011103111310f320f3212000d05000000000000",
                                "26": "2600f2001400024b6300012510111130110f120f1110110f120f110f120f1130120f1111103110101011103111301230113011301110110f120f1110110f11111010111010100f1210111010120f1110110f120f110f120f1110110f120f1110110f11111010111010100f1210111010120f110f123011301130122f1261620001251230111011100f111011101110101110110f122f120f120f11301130120f1131101110310f321031122f123011301130122f120f1110110f123011310f32101011101110110f120f11101130110f123011301131101110310f32101110101110110f120f1110110f122f12301130113110000d05000000000000",
                                "27": "2600f2001500024b6200012511101131101011101011110f1110110f120f1130120f11101130110f120f113012301131103111301110110f120f110f120f1110110f120f1110110f111011101110101011101011110f120f1110110f120f110f120f1110110f120f1110110f11101110111010101131103111301131116162000125122f120f1110110f120f11101110111010101130120f1110110f1230110f122f120f1130122f123011301131103210301230110f120f1110113011301130120f111011101011101010311230110f122f123011301110113110301110111011101010111010111010113111301130113012000d05000000000000",
                                "28": "2600f2001400024b63000125110f1230110f11101110111010101110101110311110110f122f120f111011301130113012301131101010111010120f1110110f120f1110110f120f110f120f1110110f120f111011101011101010111010120f1110110f120f110f120f1110110f120f1110110f12301130113110311161630001251130120f110f120f1110110f120f1110110f11301210101011310f3210101230110f122f1230113011301230113110311031101110101110113011301230110f120f1110110f11101110111010310f3210311131110f122f1230110f120f1110110f120f1110111010310f321032103111000d05000000000000",
                                "29": "2600f2001300024c63000125110f122f120f11101110110f11111010111010310f1210101031120f1110113011301130123011301110101110110e120f1210101011101110101110101011101110101011101011101011110f1110110f120e120d140f110f12101110101110101011101011101011311031103110321062620001260f3210111010111011101010111010111010113011101011101110310e130d340f121031103111301131103110311131103110110d140d130f330f3210311011101011101011101011301110103210310e330f331010113011311010111010111010111010111010103111310e340f3210000d05000000000000",
                                "30": "2600f2001400024b6300012511101130111011101010120f1111100f120f1130120f110f1230110f120f113011301230113011311110110f1110110f120f1110110f120f110f120f1110110f121010101110101110101110110f120f1110110f120f1110110f1110110f120f1110110f121010101131103111311030126162000126112f120f1110110f120f1110111010111010113011101110110f122f120f1130120f1130122f123011301131103111311130110f120f1110113011301130120f1110111010111010111010321031112f123011301110113011301110110f12101010111011101010113111301130113011000d05000000000000"
                            }
                        }
                    }
                }
```

Any ideas of what I'm might be missing?

**Comment by AxelDreemurr** [comment]
You're missing the `"on"` HEX code for both cool and heat modes.
