### ISSUE TITLE
Adding new TV crashes homebridge

### ISSUE THREAD

**Issue by dresken** [kiwi-cam/homebridge-broadlink-rm#55]
Occurs after adding to Home app. Restart and we are off again. Encountered this a few times because I kept changing the names of the TVs

14/09/2020, 10:17:51 pm [BroadlinkRM] Identify requested for TV
14/09/2020, 10:17:51 pm Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/once.js:12:19
    at Accessory.<anonymous> (/usr/lib/node_modules/@hoobs/hoobs/bridge/platform.js:57:13)
    at Accessory.emit (events.js:315:20)
    at Accessory.EventEmitter.emit (/usr/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/EventEmitter.js:60:38)
    at Accessory._this._identificationRequest (/usr/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:162:23)
    at Identify.<anonymous> (/usr/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:1094:23)
    at Identify.emit (events.js:315:20)
    at Identify.EventEmitter.emit (/usr/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/EventEmitter.js:60:38)
    at Identify.Characteristic._this.setValue (/usr/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Characteristic.js:369:23)
    at /usr/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:953:36
    at Array.forEach (<anonymous>:null:null)
    at Accessory._this._handleSetCharacteristics (/usr/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:821:18)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/EventEmitter.js:60:38)
    at HAPServer._this._handleCharacteristics (/usr/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:731:23)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:240:39)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by kiwi-cam** [comment]
This is an odd one... and I suspect nothing to do with this module. The stack trace above doesn't include any code from this plugin.

Are you still having this issue?
