### ISSUE TITLE
 homebridge-broadlink-rm stopped working "log is not a function" now have 0 accessories

### ISSUE THREAD

**Issue by jasehigh** [kiwi-cam/homebridge-broadlink-rm#600]
I've been using the homebridge-broadlink-rm plugin for years without issue. Restarted my Mac mini server today and this homebridge instance would not run.

Running in DEBUG mode I could see the following error.

```
TypeError: log is not a function
    at /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/helpers/checkForUpdates.js:16:7
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/github-version-checker/lib/query/rest.js:69:17)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

Couldn't fix the issue so decided to remove the bridge from my home, delete the "accessories" and "persist" directories and re-add the bridge. However, now when I add the bridge, the bridge appears in the Home app, but no accessories are present.

My config.json file has not changed (presented below).

There appears to be some confusion in the plugin name, as I see this error when starting:

`The requested platform 'BroadlinkRM' has been registered multiple times. Please be more specific by writing one of: homebridge-broadlink-rm.BroadlinkRM, homebridge-broadlink-rm-pro.BroadlinkRM`

I can see two plugins installed:
homebridge-broadlink-rm 3.6.22
homebridge-broadlink-rm-pro 4.4.12

Any assistance in understanding this problem is greatly appreciated.

Jason.

```
{
	"bridge": {
		"name": "Broadlink",
		"username": "CC:22:3D:E3:CE:32",
		"port": 51827,
		"pin": "031-45-155"
	},
	"accessories": [],
	"platforms": [{
		"platform": "BroadlinkRM",
		"name": "Broadlink RM",
		"hideScanFrequencyButton": true,
		"hideLearnButton": true,
		"homebridgeDirectory": "/Users/admin/.broadlink",
		"accessories": [{
			"name": "Light",
			"host": "10.0.1.8",
			"type": "switch",
			"data": {
				"on": [{
						"data": "260038012a0e2a0e0e290f290f290e290f290f292a0e0e290f290f0001082a0e2a0e0e290f290e290f290f290f292a0e0e290f290e0001082b0e2a0d0f290e290f290f290e290f292b0d0f290e290f0001082a0e2b0d0e290f290f290e290f290f292a0e0f280f290f0001082a0e2a0e0e290f290f280f290f290f292a0e0e290f290e0001082b0e2a0d0f290e290f290f290e2a0e292b0e0e290e2a0e0001082b0d2b0d0f280f290f290f290e290f292b0d0f290e290f0001082a0e2a0e0e290f290f290e290f290f292a0e0e290f290e0001092a0e2a0e0e290f290e290f290f290e2a2a0e0e290f290e0001082b0e2a0d0f290e290f290e2a0e2a0e290f290e2a0e2a0e0001082b0d2b0d0e290f290f290e290f290f290f290e290f290f0001082b0d2a0e0e290f290e290f290f290f290e290f290f290f000d05"
					}
				],
				"off": [{
						"data": "260038012a0e2a0e0e290f290f290e290f290f292a0e0e290f290f0001082a0e2a0e0e290f290e290f290f290f292a0e0e290f290e0001082b0e2a0d0f290e290f290f290e290f292b0d0f290e290f0001082a0e2b0d0e290f290f290e290f290f292a0e0f280f290f0001082a0e2a0e0e290f290f280f290f290f292a0e0e290f290e0001082b0e2a0d0f290e290f290f290e2a0e292b0e0e290e2a0e0001082b0d2b0d0f280f290f290f290e290f292b0d0f290e290f0001082a0e2a0e0e290f290f290e290f290f292a0e0e290f290e0001092a0e2a0e0e290f290e290f290f290e2a2a0e0e290f290e0001082b0e2a0d0f290e290f290e2a0e2a0e290f290e2a0e2a0e0001082b0d2b0d0e290f290f290e290f290f290f290e290f290f0001082b0d2a0e0e290f290e290f290f290f290e290f290f290f000d05"
					}
				]
			}
		}, {
			"name": "Dim",
			"host": "10.0.1.8",
			"type": "switch",
			"enableAutoOff": true,
			"onDuration": 1,
			"data": [{
				"data": "260084032c0c2e0a10271127102810282c0b1127102810281027110001062c0c2d0a11271127102810272d0b1127102810271127100001072c0b2e0a11271028102711272c0c1127102711271028100001062d0b2d0b11271027112710282c0c1027112710281027110001062c0c2c0c10271127112710282c0b1127102810271127100001072c0c2c0b11271028102810272c0c1127102711271127100001072c0b2d0b10281027112711272c0c1027112710281028100001062d0b2c0c10271127112710282c0b1127102810281027110001062c0c2c0b11271127102810272d0b1028102810271127100001072c0b2c0c10281028102711272c0c1028102711271028100001062d0b2c0c10281027112710282c0c1027112710281027110001062c0c2c0c10271127102810282c0b1127102810271127100001072c0c2c0b11270f290f290f282b0d0e2a0f2810280f290f0001082a0d2b0d0e2a0f290f280f292a0e0e290f290f290f290f0001072a0e2a0e0e2a0e290e2a0e2a2a0d0f290f290e2a0e290e0001092a0e2a0e0e290e2a0e2a0e292a0e0e2a0e2a0e290e2a0e0001092a0e290e0e2a0e2a0e290f292a0e0f290f280f290e2a0f0001072b0d2b0d0f290f280f290f292b0d0f280f290f290f290f0001072b0d2b0d0e290f290f290f292a0d0f290f290f290f280f0001082b0d2b0c0f290f290f290f282b0d0f290f290f280f290f0001082b0c2b0d0f290f290f280f292b0d0f290f280f290f290f0001072b0d2b0d0f290f280f290f292b0d0f280f290f290f280f0001082b0d2b0d0f280f290f290f292a0d0f290f290f280f290f0001082b0d2a0d0f290f290f290e292b0e0e290f280f290f290f0001082a0e2a0e0e290f290e290f292b0e0e280f290f290f290f0001072b0e2a0e0e290e290f290f292b0d0e290f290f290e290f0001082b0e2a0d0e2a0e2a0e2a0e292a0e0e2a0e290e2a0e2a0e000109290e2a0e0e2a0e2a0e290e2a2a0e0e290e2a0e2a0e2a0e0001082a0e2a0e0e2a0d2a0e2a0e2a2a0d0e2a0e2a0e2a0e290e0001092a0e2a0e0d2a0e2a0e2a0e292a0e0d2b0e2a0d2b0d2a0d00010a290f28100c2b0d2c0c2b0d2b28100c2b0d2b0d2b0c2c0c00010a281028100c2c0c2b0c2c0c2c28100c2b0c2c0c2c0c2b0d00010b271127100c2c0b2d0b2d0b2c27110b2d0b2d0b2c0b2d0b00010d261126120a2e0a2e0a2d0b2d2613092e0a2e0a2e092f0900010f23152314083106320632053322000d0500000000",
				"sendCount": 2,
				"interval": 0.1
			}]
		}, {
			"name": "Fan",
			"host": "10.0.1.8",
			"type": "fan",
			"hideRotationDirection": true,
			"hideSwingMode": true,
			"data": {
				"on": "260084012b0d2a0f0d2a0e290f292a0f0d2a0e290f290e2a2a0e2aec2a0f290e0e290f290e2a2a0f0d2a0e290e2a0e2a2a0e29ed2a0e2a0e0e290e2a0e2a2a0d0f290e2a0e2a0e292a0f29ed2a0e290e0e2a0e2a0e292a0f0d2a0e2a0e2a0d2a2a0f29ec2a0f290f0d2a0e290f292a0e0e2a0e290e2a0e2a2a0e2aec2a0f290e0e290f2a0d2a2a0e0e290e2a0e2a0e292b0d2aed2a0e2a0d0e2a0e2a0e292b0e0d2a0e2a0e290f292a0e2aec2b0d2a0e0e2a0e2a0e292a0f0d2a0e290f290f292a0e2aec2a0e2a0e0e2a0e290e2a2a0f0d290f290e2a0e2a2a0d2aed2a0e2a0e0e290e2a0e2a2a0e0e290e2a0e2a0e292a0e2aed2a0e2a0e0d2a0e2a0e292b0d0e2a0e2a0e290f292a0f29ec2b0e290e0e2a0e290f292a0f0d2a0e290f290e2b290e2aec2a0f290e0e290f290e2a2a0e0e290f290e2a0e2a2a0e29ed2a0f290e0e290e2a0e2a2a0d0f290e2a0e2a0e292a0e2ceb2a0e290f0d2a0e2a0e290f290e2a0e2a0e290e2a0e2a0e0001082a0e2a0f0d2a0e290f290e2a0e2a0e290e2a0e2a0e2a0e000d0500000000",
				"off": "2600a0012a0e2a0e0e290e2a0e2a0e290e2a2a0f0d2a0e290e2a0e0001092a0e290e0e2a0e2a0e290e2a0e2a2a0e0e2a0d2b0d2a0e0001082a0f290f0d2a0e290e2a0e2a0e292b0d0e2a0e2a0e290f0001082a0e2a0e0e290e2a0e2a0e290f292a0e0e2a0e290f290e0001092a0e2a0d0e2a0e2a0e290f290e2a2a0f0d290f290e2a0e0001082b0e290f0d2a0e290f290e2a0e2a2a0d0f290e2a0e2a0e0001082a0e2a0e0e290f290e2a0e2a0e292a0f0d2a0e2a0e290f0001082a0f290e0e290e2a0e2a0e290f292a0e0e2a0e290f290e0001092a0e2a0d0e2a0e2b0d290f290e2a2a0e0e290f290e2a0e0001082b0d2a0e0e2a0e290f290e2a0e2a2a0e0e290e2a0e2a0e0001082a0f290e0e290f290e2a0e2a0e292a0e0e2a0e2a0e290e0001092a0f290e0e290e2a0e2a0e290f2a290f0d2a0e290e2a0e0001092a0e2a0e0d2a0e2a0e290f290e2a2a0e0e290f290e2a0e0001082a0f290e0e2a0e290f290e2a0e2a2a0d0e2a0e2a0e290f0001082a0f290e0e290f2a0d2a0e2a0e290e2a0e2a0e2a0e290e0001092a0f290d0f2a0d2a0e2a0e290e2a0e2a0e290f290e2a0e000d050000000000000000",
				"fanSpeed10": "260084012b0d2a0f0d2a0e290f292a0f0d2a0e290f290e2a2a0e2aec2a0f290e0e290f290e2a2a0f0d2a0e290e2a0e2a2a0e29ed2a0e2a0e0e290e2a0e2a2a0d0f290e2a0e2a0e292a0f29ed2a0e290e0e2a0e2a0e292a0f0d2a0e2a0e2a0d2a2a0f29ec2a0f290f0d2a0e290f292a0e0e2a0e290e2a0e2a2a0e2aec2a0f290e0e290f2a0d2a2a0e0e290e2a0e2a0e292b0d2aed2a0e2a0d0e2a0e2a0e292b0e0d2a0e2a0e290f292a0e2aec2b0d2a0e0e2a0e2a0e292a0f0d2a0e290f290f292a0e2aec2a0e2a0e0e2a0e290e2a2a0f0d290f290e2a0e2a2a0d2aed2a0e2a0e0e290e2a0e2a2a0e0e290e2a0e2a0e292a0e2aed2a0e2a0e0d2a0e2a0e292b0d0e2a0e2a0e290f292a0f29ec2b0e290e0e2a0e290f292a0f0d2a0e290f290e2b290e2aec2a0f290e0e290f290e2a2a0e0e290f290e2a0e2a2a0e29ed2a0f290e0e290e2a0e2a2a0d0f290e2a0e2a0e292a0e2ceb2a0e290f0d2a0e2a0e290f290e2a0e2a0e290e2a0e2a0e0001082a0e2a0f0d2a0e290f290e2a0e2a0e290e2a0e2a0e2a0e000d0500000000",
				"fanSpeed20": "260084012b0d2a0f0d2a0e290f292a0f0d2a0e290f290e2a2a0e2aec2a0f290e0e290f290e2a2a0f0d2a0e290e2a0e2a2a0e29ed2a0e2a0e0e290e2a0e2a2a0d0f290e2a0e2a0e292a0f29ed2a0e290e0e2a0e2a0e292a0f0d2a0e2a0e2a0d2a2a0f29ec2a0f290f0d2a0e290f292a0e0e2a0e290e2a0e2a2a0e2aec2a0f290e0e290f2a0d2a2a0e0e290e2a0e2a0e292b0d2aed2a0e2a0d0e2a0e2a0e292b0e0d2a0e2a0e290f292a0e2aec2b0d2a0e0e2a0e2a0e292a0f0d2a0e290f290f292a0e2aec2a0e2a0e0e2a0e290e2a2a0f0d290f290e2a0e2a2a0d2aed2a0e2a0e0e290e2a0e2a2a0e0e290e2a0e2a0e292a0e2aed2a0e2a0e0d2a0e2a0e292b0d0e2a0e2a0e290f292a0f29ec2b0e290e0e2a0e290f292a0f0d2a0e290f290e2b290e2aec2a0f290e0e290f290e2a2a0e0e290f290e2a0e2a2a0e29ed2a0f290e0e290e2a0e2a2a0d0f290e2a0e2a0e292a0e2ceb2a0e290f0d2a0e2a0e290f290e2a0e2a0e290e2a0e2a0e0001082a0e2a0f0d2a0e290f290e2a0e2a0e290e2a0e2a0e2a0e000d0500000000",
				"fanSpeed30": "260084012b0d2a0f0d2a0e290f292a0f0d2a0e290f290e2a2a0e2aec2a0f290e0e290f290e2a2a0f0d2a0e290e2a0e2a2a0e29ed2a0e2a0e0e290e2a0e2a2a0d0f290e2a0e2a0e292a0f29ed2a0e290e0e2a0e2a0e292a0f0d2a0e2a0e2a0d2a2a0f29ec2a0f290f0d2a0e290f292a0e0e2a0e290e2a0e2a2a0e2aec2a0f290e0e290f2a0d2a2a0e0e290e2a0e2a0e292b0d2aed2a0e2a0d0e2a0e2a0e292b0e0d2a0e2a0e290f292a0e2aec2b0d2a0e0e2a0e2a0e292a0f0d2a0e290f290f292a0e2aec2a0e2a0e0e2a0e290e2a2a0f0d290f290e2a0e2a2a0d2aed2a0e2a0e0e290e2a0e2a2a0e0e290e2a0e2a0e292a0e2aed2a0e2a0e0d2a0e2a0e292b0d0e2a0e2a0e290f292a0f29ec2b0e290e0e2a0e290f292a0f0d2a0e290f290e2b290e2aec2a0f290e0e290f290e2a2a0e0e290f290e2a0e2a2a0e29ed2a0f290e0e290e2a0e2a2a0d0f290e2a0e2a0e292a0e2ceb2a0e290f0d2a0e2a0e290f290e2a0e2a0e290e2a0e2a0e0001082a0e2a0f0d2a0e290f290e2a0e2a0e290e2a0e2a0e2a0e000d0500000000",
				"fanSpeed40": "260084012b0d2a0f0d2a0e290f292a0f0d2a0e290f290e2a2a0e2aec2a0f290e0e290f290e2a2a0f0d2a0e290e2a0e2a2a0e29ed2a0e2a0e0e290e2a0e2a2a0d0f290e2a0e2a0e292a0f29ed2a0e290e0e2a0e2a0e292a0f0d2a0e2a0e2a0d2a2a0f29ec2a0f290f0d2a0e290f292a0e0e2a0e290e2a0e2a2a0e2aec2a0f290e0e290f2a0d2a2a0e0e290e2a0e2a0e292b0d2aed2a0e2a0d0e2a0e2a0e292b0e0d2a0e2a0e290f292a0e2aec2b0d2a0e0e2a0e2a0e292a0f0d2a0e290f290f292a0e2aec2a0e2a0e0e2a0e290e2a2a0f0d290f290e2a0e2a2a0d2aed2a0e2a0e0e290e2a0e2a2a0e0e290e2a0e2a0e292a0e2aed2a0e2a0e0d2a0e2a0e292b0d0e2a0e2a0e290f292a0f29ec2b0e290e0e2a0e290f292a0f0d2a0e290f290e2b290e2aec2a0f290e0e290f290e2a2a0e0e290f290e2a0e2a2a0e29ed2a0f290e0e290e2a0e2a2a0d0f290e2a0e2a0e292a0e2ceb2a0e290f0d2a0e2a0e290f290e2a0e2a0e290e2a0e2a0e0001082a0e2a0f0d2a0e290f290e2a0e2a0e290e2a0e2a0e2a0e000d0500000000",
				"fanSpeed50": "260038012a0f290d0f290e2a0e2a0e2a0d2a0e2a0e2a2a0e0d2b0d0001082b0d2a0e0e2a0e2a0e290e2a0e2a0e2a0e292a0f0d2a0e0001082a0e2a0f0d2a0e290e2a0e2a0e290f2a0d2a2a0f0d290f0001082a0f290e0e290e2b0d2a0e290f290e2b0d2a2a0e0e290e00010a290e2a0e0d2a0e2a0e290f290e2b0d2a0e292a0e0e2a0e0001082b0e290e0e2a0e2a0e290e2a0e2a0e290f292a0e0e2a0e0001082a0e2a0e0e290f290e2a0e2a0e290f290e2a2a0e0e290e0001092a0f290e0e290e2a0e2a0e290f290e2a0e2a2a0d0e2a0e0001092a0e290f0d2a0e2a0e290f290e2a0e2a0e292a0e0e2a0e0001082a0e2a0e0e2a0e290f290e2a0e2a0e290e2a2a0f0d290f0001082a0f290e0e290f290e2a0e2a0e290e2a0e2a2a0e0e290e0001092a0e2a0e0e290e2a0e2a0e2a0d2a0e2a0e2a2a0d0e2a0e000d05",
				"fanSpeed60": "260038012a0f290d0f290e2a0e2a0e2a0d2a0e2a0e2a2a0e0d2b0d0001082b0d2a0e0e2a0e2a0e290e2a0e2a0e2a0e292a0f0d2a0e0001082a0e2a0f0d2a0e290e2a0e2a0e290f2a0d2a2a0f0d290f0001082a0f290e0e290e2b0d2a0e290f290e2b0d2a2a0e0e290e00010a290e2a0e0d2a0e2a0e290f290e2b0d2a0e292a0e0e2a0e0001082b0e290e0e2a0e2a0e290e2a0e2a0e290f292a0e0e2a0e0001082a0e2a0e0e290f290e2a0e2a0e290f290e2a2a0e0e290e0001092a0f290e0e290e2a0e2a0e290f290e2a0e2a2a0d0e2a0e0001092a0e290f0d2a0e2a0e290f290e2a0e2a0e292a0e0e2a0e0001082a0e2a0e0e2a0e290f290e2a0e2a0e290e2a2a0f0d290f0001082a0f290e0e290f290e2a0e2a0e290e2a0e2a2a0e0e290e0001092a0e2a0e0e290e2a0e2a0e2a0d2a0e2a0e2a2a0d0e2a0e000d05",
				"fanSpeed70": "260038012a0f290d0f290e2a0e2a0e2a0d2a0e2a0e2a2a0e0d2b0d0001082b0d2a0e0e2a0e2a0e290e2a0e2a0e2a0e292a0f0d2a0e0001082a0e2a0f0d2a0e290e2a0e2a0e290f2a0d2a2a0f0d290f0001082a0f290e0e290e2b0d2a0e290f290e2b0d2a2a0e0e290e00010a290e2a0e0d2a0e2a0e290f290e2b0d2a0e292a0e0e2a0e0001082b0e290e0e2a0e2a0e290e2a0e2a0e290f292a0e0e2a0e0001082a0e2a0e0e290f290e2a0e2a0e290f290e2a2a0e0e290e0001092a0f290e0e290e2a0e2a0e290f290e2a0e2a2a0d0e2a0e0001092a0e290f0d2a0e2a0e290f290e2a0e2a0e292a0e0e2a0e0001082a0e2a0e0e2a0e290f290e2a0e2a0e290e2a2a0f0d290f0001082a0f290e0e290f290e2a0e2a0e290e2a0e2a2a0e0e290e0001092a0e2a0e0e290e2a0e2a0e2a0d2a0e2a0e2a2a0d0e2a0e000d05",
				"fanSpeed80": "260038012a0f290d0f290e2a0e2a0e2a0d2a0e2a0e2a2a0e0d2b0d0001082b0d2a0e0e2a0e2a0e290e2a0e2a0e2a0e292a0f0d2a0e0001082a0e2a0f0d2a0e290e2a0e2a0e290f2a0d2a2a0f0d290f0001082a0f290e0e290e2b0d2a0e290f290e2b0d2a2a0e0e290e00010a290e2a0e0d2a0e2a0e290f290e2b0d2a0e292a0e0e2a0e0001082b0e290e0e2a0e2a0e290e2a0e2a0e290f292a0e0e2a0e0001082a0e2a0e0e290f290e2a0e2a0e290f290e2a2a0e0e290e0001092a0f290e0e290e2a0e2a0e290f290e2a0e2a2a0d0e2a0e0001092a0e290f0d2a0e2a0e290f290e2a0e2a0e292a0e0e2a0e0001082a0e2a0e0e2a0e290f290e2a0e2a0e290e2a2a0f0d290f0001082a0f290e0e290f290e2a0e2a0e290e2a0e2a2a0e0e290e0001092a0e2a0e0e290e2a0e2a0e2a0d2a0e2a0e2a2a0d0e2a0e000d05",
				"fanSpeed90": "260038012a0f290d0f290e2a0e2a0e2a0d2a0e2a0e2a2a0e0d2b0d0001082b0d2a0e0e2a0e2a0e290e2a0e2a0e2a0e292a0f0d2a0e0001082a0e2a0f0d2a0e290e2a0e2a0e290f2a0d2a2a0f0d290f0001082a0f290e0e290e2b0d2a0e290f290e2b0d2a2a0e0e290e00010a290e2a0e0d2a0e2a0e290f290e2b0d2a0e292a0e0e2a0e0001082b0e290e0e2a0e2a0e290e2a0e2a0e290f292a0e0e2a0e0001082a0e2a0e0e290f290e2a0e2a0e290f290e2a2a0e0e290e0001092a0f290e0e290e2a0e2a0e290f290e2a0e2a2a0d0e2a0e0001092a0e290f0d2a0e2a0e290f290e2a0e2a0e292a0e0e2a0e0001082a0e2a0e0e2a0e290f290e2a0e2a0e290e2a2a0f0d290f0001082a0f290e0e290f290e2a0e2a0e290e2a0e2a2a0e0e290e0001092a0e2a0e0e290e2a0e2a0e2a0d2a0e2a0e2a2a0d0e2a0e000d05",
				"fanSpeed100": "260024012a0e290e0e2a0e2a0e290f290e2a0e2a0e290e2a0e2a2aec2a0f290f0d2a0e290f290e2a0e2a0e290e2a0e2a0e292bec2a0f290e0e290f290e2a0e290f290e2a0e2a0e2a0e292aed2a0e2a0d0f290e2a0e290f290e2a0e2a0e290f290e2a2aec2b0d2a0f0d2a0e290f290e2b0d2a0e2a0e290e2a0e2a2aec2a0e2a0e0e2a0e290e2a0e2a0e290f290e2a0e2a0e292aed2a0e2a0e0e290e2a0e2a0e290f290e2a0e2a0e290f292aed2a0e2a0d0e2a0e2a0e290f290e2a0e2a0e290f290e2a2aed2a0d2a0f0d2a0e2a0e290e2a0e2a0e290f290e2a0e2a2aec2a0e2a0f0d2a0e290e2a0e2a0e290f290e2a0e2a0e2a29ed2a0e2a0e0e290e2a0e2a0e290f290e2a0e2a0e290e2a0e0001092a0e290f0d2a0e2a0e290f290e2a0e2a0e2a0d2a0e2a0e000d0500000000"
			}
		}, {
			"name": "Candles",
			"host": "10.0.1.7",
			"type": "switch",
			"data": {
				"on": [{
					"data": "2600080100012695111411141114113911141114111411141139123811391114113911391114113911141114111411141114111411141114113911391139113911391139113911391100053a0001264b12000c4c0001254c11000c4d0001254c12000c4b0001264c11000c4c0001264b12000c4c0001254c12000c4c0001254c11000c4d0001254c11000c4d0001254c11000c4c0001264c11000c4c0001264b11000c4d0001254b12000c4d0001264b12000c4c0001254c11000c4c0001264b12000c4c0001264b11000c4d0001254c11000c4d0001254c11000c4d0001254c11000c4d0001254c11000c4c0001264b12000c4c0001254c11000c4d0001254c11000c4d0001254c11000d05"
				}],
				"off": [{
					"pause": 0.2,
					"data": "2600e0000001269511141114111411391114111411141114113911391139111411391139111411391114113911141114111412131114111412381213123812381238123812381238120005390001264c11000c4c0001264b12000c4c0001264b12000c4c0001264b12000c4c0001264b12000c4c0001254c11000c4c0001254c11000c4c0001264b11000c4c0001264b11000c4c0001264b11000c4c0001254c11000c4c0001254c11000c4c0001254c11000c4c0001264b11000c4d0001254c11000c4c0001254c11000c4c0001254c11000c4c0001254c11000c4c0001264c11000d050000000000000000"
				}]
			}
		}, {
			"name": "Fire",
			"host": "10.0.1.7",
			"type": "switch",
			"data": {
				"on": [{
						"data": "26004800000129921411151014111411141114111411141114341535143515341535143515341535141115101411141114351435151114111434153415351435151114111434153415000d05",
						"pause": 0.2
					},
					{
						"data": "26004800000129911510131215101510151013121411141112371534153514351534153512371534131213121312131215341510133714111435143515351435141114351510153415000d05",
						"pause": 0.2
					},
					{
						"data": "26004800000129921511141114111411131114111411141114351435153415351435153415341634151114111411131115341511143415111434153514351534151114351411143515000d05",
						"pause": 0.2
					},
					{
						"data": "2600480000012a921412131213111411141114111411141114341535143515341535143515341535141213111411141114351412133515111434153415351534151114341511143514000d05"
					}
				],
				"off": [{
						"data": "2600480000012a921510141114111411141114111411141114341535143515341535143515341535141114111411141114351411141115101435143515341634151014351534153415000d05"
					}
				]
			}
		}, {
			"name": "IR",
			"host": "10.0.1.7",
			"type": "switch",
			"data": {
				"on": [{
						"data": "26004800000129921411151014111411141114111411141114341535143515341535143515341535141115101411141114351435151114111434153415351435151114111434153415000d05",
						"pause": 0.2
					},
					{
						"data": "26004800000129911510131215101510151013121411141112371534153514351534153512371534131213121312131215341510133714111435143515351435141114351510153415000d05",
						"pause": 0.2
					},
					{
						"data": "26004800000129921511141114111411131114111411141114351435153415351435153415341634151114111411131115341511143415111434153514351534151114351411143515000d05",
						"pause": 0.2
					},
					{
						"data": "2600480000012a921412131213111411141114111411141114341535143515341535143515341535141213111411141114351412133515111434153415351534151114341511143514000d05",
						"pause": 0.2
					},
					{
						"data": "2600080100012695111411141114113911141114111411141139123811391114113911391114113911141114111411141114111411141114113911391139113911391139113911391100053a0001264b12000c4c0001254c11000c4d0001254c12000c4b0001264c11000c4c0001264b12000c4c0001254c12000c4c0001254c11000c4d0001254c11000c4d0001254c11000c4c0001264c11000c4c0001264b11000c4d0001254b12000c4d0001264b12000c4c0001254c11000c4c0001264b12000c4c0001264b11000c4d0001254c11000c4d0001254c11000c4d0001254c11000c4d0001254c11000c4c0001264b12000c4c0001254c11000c4d0001254c11000c4d0001254c11000d05"
					}
				],
				"off": [{
						"data": "2600480000012a921510141114111411141114111411141114341535143515341535143515341535141114111411141114351411141115101435143515341634151014351534153415000d05",
						"pause": 0.2
					},
					{
						"data": "2600e0000001269511141114111411391114111411141114113911391139111411391139111411391114113911141114111412131114111412381213123812381238123812381238120005390001264c11000c4c0001264b12000c4c0001264b12000c4c0001264b12000c4c0001264b12000c4c0001254c11000c4c0001254c11000c4c0001264b11000c4c0001264b11000c4c0001264b11000c4c0001254c11000c4c0001254c11000c4c0001254c11000c4c0001264b11000c4d0001254c11000c4c0001254c11000c4c0001254c11000c4c0001254c11000c4c0001264c11000d050000000000000000"
					}
				]
			}
		}, {
			"name": "Heat",
			"host": "10.0.1.7",
			"type": "switch",
			"data": {
				"on": [{
						"data": "26004800000129921510131214111312141112131212131215351435143515341535143514351535141114111410151015101534153515101435123715351435163315101510123713000d05"
					}
				],
				"off": [{
						"data": "26004800000129921411141114111213121314101312131215351435143515341337143514351535141112371411121314111212151015101337141013371435143515351435143513000d05",
						"pause": 0.2
					},
					{
						"data": "26004800000129921411141114111213121314101312131215351435143515341337143514351535141112371411121314111212151015101337141013371435143515351435143513000d05"
					}
				]
			}
		}]
	}]
}
```

**Comment by jasehigh** [comment]
I uninstalled homebridge-broadlink-rm-pro, deleted the  "accessories" and "persist" directories again, and this time everything seemed to work as expected, with the accessories being added since I added the bridge.
