### ISSUE TITLE
Homebridge reboots when trying to send off command to AC

### ISSUE THREAD

**Issue by ghost** [kiwi-cam/homebridge-broadlink-rm#615]
Homebridge reboots itself when trying to turn the AC off.
This is the status log from homebridge:
```
[25-6-2023 09:27:31] [Broadlink Mini] Airco No off HEX code found for 20
[25-6-2023 09:27:31] AssertionError: [CONFIG ERROR]  You need to provide a hex code for the following temperature:
        { "temperature20": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } }
        or provide the default temperature:
         { "temperature16": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } }
    at AirConAccessory.getTemperatureHexData (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:363:7)
    at AirConAccessory.sendTemperature (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:323:48)
    at AirConAccessory.setTargetTemperature (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/aircon.js:195:10)
    at AirConAccessory.setCharacteristicValue (/usr/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:145:9)
    at TargetTemperature.emit (node:events:513:28)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2596:16
    at new Promise (<anonymous>)
    at TargetTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2594:14)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:193:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:174:57)
[25-6-2023 09:27:31] Got SIGTERM, shutting down Homebridge...
[25-6-2023 09:27:36] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[25-6-2023 09:27:41] [HB Supervisor] Restarting Homebridge...
```
This is my config
```
{
            "platform": "BroadlinkRM",
            "name": "Broadlink Mini",
            "hideScanFrequencyButton": true,
            "hideLearnButton": true,
            "hideWelcomeMessage": true,
            "hosts": [
                {
                    "address": "192.168.xx.xxx",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "isRFSupported": true,
                    "isRM4": true
                }
            ],
            "accessories": [
                {
                    "name": "Slaapkamer Temp",
                    "type": "temperatureSensor",
                    "logLevel": "warning"
                },
                {
                    "name": "Airco",
                    "type": "air-conditioner",
                    "noHumidity": true,
                    "minTemperature": 17,
                    "maxTemperature": 22,
                    "allowResend": false,
                    "preventResendHex": true,
                    "logLevel": "warning",
                    "data": {
                        "off": "2600ca008e8f13341311133512351311121212351311131112351311131113341334131113351311123513341335133413111334133513341311131113111311123513111212123513341335131112111311131113111311131112111335133413341335133412ac918e13341311133513341311131112351311131113341311131113341334131113351311133413341335133413111334133513341311131113111311123513111311123513341335131112121211131113111311131112111335133413351235133413000d05000000000000000000000000",
                        "cool17": {
                            "pseudo-mode": "cool",
                            "data": "2600ca008e8f13351311123513351211131113341311131113351212121113351235131113341335131113341335123513341335123513111334131113111311131112121211131113111311121212111311131113111334133512351334133512351334133512aa928e13341311133413351212121212351212131112351311121212351334131113351235131113341335133413351235133413111335121113111311131112121212121113111311131112121211131113111334133512351334133513341334133512000d05000000000000000000000000"
                        },
                        "cool18": {
                            "pseudo-mode": "cool",
                            "data": "2600ca008f8f12351311123513351211131113341311131113351212121113351235131113341335131112351335123513341335123513111334131113111311121212111311131113111311123513111212121113111335123513341311133512351334133512ab918f12351311133413351211131113351211131113351311121113351235131113341335131112351335123513341335123513111334131113111311121113111311131113111212123513111211131113111335123513341311133512351334133512000d05000000000000000000000000"
                        },
                        "cool19": {
                            "pseudo-mode": "cool",
                            "data": "2600ca008f8f13341311133413351311121113351311121113351311131112351334131113351235131113341335133413341335133413111334131113111311131112111311131113111334133513111211131113111334133513111311123513341334133512ab918f13341311133413351311121113351311121212351311131112351334131113351235131113341335133413341335133413111334131113111311131112111311131113111334133513111211131113111335123513111311123513341335133412000d05000000000000000000000000"
                        },
                        "cool20": {
                            "pseudo-mode": "cool",
                            "data": "2600ca008f8f13341311133413351311121113351311121113351311131112351334131113341335131113341335133413341335133413111334131113111311131112111311131113111334131113111311131013111335133413111334133513341334133512ab918e14341311133413341311131113341311131113351311121113351334131113341335131113341335123513341335123513111334131113111311131013111311131113111334131113111311131013111335133413111334133513341334133512000d05000000000000000000000000"
                        },
                        "cool21": {
                            "pseudo-mode": "cool",
                            "data": "2600ca008f8e13351311133413341311131113341311131113351311121113351334131113341335131113341334133513341334133513111334131113111311131013111311131113341335131014101311131113111334131113111334133413351334133413aa918e13351311133413341311131113341311131113341410131113341335131113341335131112351334133513341334133513111334131113111311121113111311131113341334131113121211131113111235131113111334133413351334133413000d05000000000000000000000000"
                        }
                    }
                },
                {
                    "name": "AC - Turbo",
                    "logLevel": "warning",
                    "type": "switch",
                    "data": {
                        "on": "2600ca008c9112361212113610371212133511121335111311361113111312351113113612121236113612351335121111371113103713111311121212111434111312351311123514101335131013111311133512111410133513111235143314341310133510ad918e13341410143314341311133414101334141014341311131014341310143413111532143314341334131113341311143413111310141014101334141014341311133413111334131114101311133414101311133414101434133413341410143410000d05000000000000000000000000",
                        "off": "2600ca008e9012361113113613341311123612111236131111361212111311361212113613111235123611361335111212361212113612121212111311121236121211361311123513111236121211121212123513111212123612121235133413351212123512ab908f13341311133512351311123513111335121212351212121113351311123513111334133512351334131113351211133513111212121113111335121113351311123513111334131113111311123513111311133413111335133413341311133512000d05000000000000000000000000"
                    }
                },
                {
                    "name": "AC - Scherm uit",
                    "logLevel": "warning",
                    "type": "switch",
                    "data": {
                        "on": "2600ca008c9112351212123611371112123512121236121210371212111310371212113612121236113612351236111211371212103712121113111310141037121210371212123610131236111310141037111311361212103712121136123612121136121212ab8f9012361211123612351311123611121236121211361212111311361212113612121236113612351236111212361212113613111212111311131136121211361212123513111236121211121236121211361212113613111235123611131136131112000d05000000000000000000000000",
                        "off": "2600ca008d9111361113113710371113103711131137101410371014101311371014103711131037113710371037111311371013113710141014101311131137101311371014103711131037111311131136111311371014103710141037113611131137101412aa8f9110371113103711371014103711131037111311361113111311361113113710141037113611371037111310371113113710141013111311131035131311371014103710141037111310141037111310371113113710131137103711131136111313000d05000000000000000000000000"
                    }
                },
                {
                    "name": "AC - Fluister Modus",
                    "logLevel": "warning",
                    "type": "switch",
                    "data": {
                        "on": "2600ca008c9111371014103711361113113710131137101410371113101410371014103711131136113710371136111311371013113710141014101311131137101311351214103711131037113710131236103711131212123511131212123512121212123512ab908f11361113123612351212123512121236121212351014121113351211133510141235113611371235111312351212123612121211121212121235121212351113133512111335123512121235133512121211133512121211133512121211133510000d05000000000000000000000000",
                        "off": "2600ca008c9210371014103711361113113710141037111310371113111310371113103711131137103710371137101311371014103711131113101410131137101410371113103711131137103710160e37113611371014103711131014103711131014101313aa8f9110371113103711371014103711131037111311361113111311361113113710141037113611371037111310371113113710141013111311131037111311371014103710141037113611131137103711361113113710131113113611131113111312000d05000000000000000000000000"
                    }
                }
            ]
        }
```
What am i doing wrong?

Homebridge v1.6.1
Broadlink plugin v4.4.13

**Comment by ghost** [comment]
Ok, so i changed my config to:
```
{
                    "name": "Airco",
                    "type": "air-conditioner",
                    "noHumidity": true,
                    "minTemperature": 17,
                    "maxTemperature": 22,
                    "defaultCoolTemperature": 20,
                    "tempStepSize": 1,
                    "coolOnly": true,
                    "allowResend": false,
                    "preventResendHex": true,
                    "logLevel": "warning",
                    "data": {
                        "off": "2600ca008e8f13341311133512351311121212351311131112351311131113341334131113351311123513341335133413111334133513341311131113111311123513111212123513341335131112111311131113111311131112111335133413341335133412ac918e13341311133513341311131112351311131113341311131113341334131113351311133413341335133413111334133513341311131113111311123513111311123513341335131112121211131113111311131112111335133413351235133413000d05000000000000000000000000",
                        "temperature17": {
                            "pseudo-mode": "cool",
                            "data": "2600ca008e8f13351311123513351211131113341311131113351212121113351235131113341335131113341335123513341335123513111334131113111311131112121211131113111311121212111311131113111334133512351334133512351334133512aa928e13341311133413351212121212351212131112351311121212351334131113351235131113341335133413351235133413111335121113111311131112121212121113111311131112121211131113111334133512351334133513341334133512000d05000000000000000000000000"
                        },
                        "temperature18": {
                            "pseudo-mode": "cool",
                            "data": "2600ca008f8f12351311123513351211131113341311131113351212121113351235131113341335131112351335123513341335123513111334131113111311121212111311131113111311123513111212121113111335123513341311133512351334133512ab918f12351311133413351211131113351211131113351311121113351235131113341335131112351335123513341335123513111334131113111311121113111311131113111212123513111211131113111335123513341311133512351334133512000d05000000000000000000000000"
                        },
                        "temperature19": {
                            "pseudo-mode": "cool",
                            "data": "2600ca008f8f13341311133413351311121113351311121113351311131112351334131113351235131113341335133413341335133413111334131113111311131112111311131113111334133513111211131113111334133513111311123513341334133512ab918f13341311133413351311121113351311121212351311131112351334131113351235131113341335133413341335133413111334131113111311131112111311131113111334133513111211131113111335123513111311123513341335133412000d05000000000000000000000000"
                        },
                        "temperature20": {
                            "pseudo-mode": "cool",
                            "data": "2600ca008f8f13341311133413351311121113351311121113351311131112351334131113341335131113341335133413341335133413111334131113111311131112111311131113111334131113111311131013111335133413111334133513341334133512ab918e14341311133413341311131113341311131113351311121113351334131113341335131113341335123513341335123513111334131113111311131013111311131113111334131113111311131013111335133413111334133513341334133512000d05000000000000000000000000"
                        },
                        "temperature21": {
                            "pseudo-mode": "cool",
                            "data": "2600ca008f8e13351311133413341311131113341311131113351311121113351334131113341335131113341334133513341334133513111334131113111311131013111311131113341335131014101311131113111334131113111334133413351334133413aa918e13351311133413341311131113341311131113341410131113341335131113341335131112351334133513341334133513111334131113111311121113111311131113341334131113121211131113111235131113111334133413351334133413000d05000000000000000000000000"
                        }
                    }
                },
```
And now at least the "homebridge is rebooting problem" is solved and not happening anymore.
I do have another issue still, the airco does not turn off when the command is given.
Homebridge status says:
```
[Broadlink RM] Airco No off HEX code found for 20
```
But the 'Off' hex is given in the config as first data point. so whats going wrong here?

**Comment by kiwi-cam** [comment]
Could you try installing the latest beta and let me know if you're still having issues?
