### ISSUE TITLE
ReferenceError: log is not defined

### ISSUE THREAD

**Issue by Janni172** [kiwi-cam/homebridge-broadlink-rm#65]
Hello! My Broadlink RM Pro Plugin worked very well.
But since yesterday i got this Error-Message.
Can you help me solve this problem? 

ReferenceError: log is not defined
    at /usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/homebridge-platform-helper/accessory.js:58:9
    at Array.forEach (<anonymous>:null:null)
    at FanAccessory.checkConfig (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/homebridge-platform-helper/accessory.js:54:25)
    at new HomebridgeAccessory (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/homebridge-platform-helper/accessory.js:35:10)
    at new BroadlinkRMAccessory (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:16:5)
    at new SwitchAccessory (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/switch.js:10:5)
    at new FanAccessory (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/fan.js:5:1)
    at /usr/lib/node_modules/homebridge-broadlink-rm-pro/platform.js:69:32
    at Array.forEach (<anonymous>:null:null)
    at BroadlinkRMPlatform.addAccessories (/usr/lib/node_modules/homebridge-broadlink-rm-pro/platform.js:64:24)
    at BroadlinkRMPlatform.accessories (/usr/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/homebridge-platform-helper/platform.js:28:10)
    at /usr/lib/node_modules/homebridge/lib/server.js:301:30
    at new Promise (<anonymous>:null:null)
    at Server.loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:296:16)
    at /usr/lib/node_modules/homebridge/lib/server.js:285:36
    at Array.forEach (<anonymous>:null:null)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:260:31)
    at Server.start (/usr/lib/node_modules/homebridge/lib/server.js:73:35)
    at cli (/usr/lib/node_modules/homebridge/lib/cli.js:88:12)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by kiwi-cam** [comment]
This error is coming from the module [homebridge-platform-helper](https://github.com/lprhodes/homebridge-platform-helper/). It looks like this exact error was [fixed in Jan](https://github.com/lprhodes/homebridge-platform-helper/issues/1#ref-commit-b149462).  

I've updated the minimum required version of this plugin in the BETA now and this will be included in the next release.
